-- ===========================================================================
-- SIGA-NNA — Esquema PostgreSQL normalizado hasta 5FN  ·  base: nnabd
-- ===========================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS auth_user (
    id           SERIAL       PRIMARY KEY,
    password     varchar(128) NOT NULL,
    last_login   timestamp with time zone NULL,
    is_superuser boolean      NOT NULL DEFAULT false,
    username     varchar(150) NOT NULL UNIQUE,
    first_name   varchar(150) NOT NULL DEFAULT '',
    last_name    varchar(150) NOT NULL DEFAULT '',
    email        varchar(254) NOT NULL DEFAULT '',
    is_staff     boolean      NOT NULL DEFAULT false,
    is_active    boolean      NOT NULL DEFAULT true,
    date_joined  timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION set_fecha_actualizacion()
RETURNS TRIGGER AS $$
BEGIN
    NEW.fecha_actualizacion = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ===========================================================================
-- CATÁLOGO GEOGRÁFICO (SEPOMEX)
-- ===========================================================================

CREATE TABLE web_entidadfederativa (
    id          bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clave       varchar(2)   NOT NULL UNIQUE,
    nombre      varchar(100) NOT NULL,
    abreviatura varchar(10)  NOT NULL
);

CREATE TABLE web_municipio (
    id         bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    entidad_id bigint NOT NULL,
    clave      varchar(5)   NOT NULL,
    nombre     varchar(150) NOT NULL
);

CREATE TABLE web_tipoasentamiento (
    id     bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(80) NOT NULL UNIQUE
);

CREATE TABLE web_asentamiento (
    id                   bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    municipio_id         bigint NOT NULL,
    tipo_asentamiento_id bigint NULL,
    nombre               varchar(200) NOT NULL,
    codigo_postal        varchar(5)   NOT NULL,
    ciudad               varchar(150) NOT NULL,
    CONSTRAINT uniq_asentamiento_municipio_cp_nombre UNIQUE (municipio_id, codigo_postal, nombre)
);

CREATE TABLE web_domicilio (
    id               bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    asentamiento_id  bigint NOT NULL,
    calle            varchar(200) NOT NULL,
    numero_exterior  varchar(20)  NOT NULL,
    numero_interior  varchar(20)  NOT NULL,
    referencias      text         NOT NULL
);

-- ===========================================================================
-- CATÁLOGOS BASE
-- ===========================================================================

CREATE TABLE web_sexo (
    id          bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clave       varchar(3)  NOT NULL UNIQUE,
    nombre      varchar(80) NOT NULL UNIQUE,
    descripcion text        NOT NULL
);

CREATE TABLE web_nacionalidad (
    id          bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clave       varchar(3)   NOT NULL UNIQUE,
    nombre      varchar(100) NOT NULL UNIQUE,
    descripcion text         NOT NULL
);

CREATE TABLE web_tipocontacto (
    id          bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clave       varchar(30)  NOT NULL UNIQUE,
    nombre      varchar(100) NOT NULL UNIQUE,
    descripcion text         NOT NULL
);

CREATE TABLE web_nivelcompetenciaoral (
    id                  bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clave               varchar(30)  NOT NULL UNIQUE,
    nombre              varchar(100) NOT NULL UNIQUE,
    significado         text         NOT NULL,
    puede_declarar      boolean      NOT NULL,
    requiere_interprete boolean      NOT NULL
);

CREATE TABLE web_modoadquisicionlengua (
    id          bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clave       varchar(30)  NOT NULL UNIQUE,
    categoria   varchar(100) NOT NULL,
    descripcion text         NOT NULL,
    contexto    text         NOT NULL
);

-- ===========================================================================
-- CATÁLOGO LINGÜÍSTICO (INALI)
-- Jerarquía: FamiliaLinguistica → Lengua
-- La variante específica del NNA se captura como texto libre en web_idiomanna.
-- ===========================================================================

CREATE TABLE web_familialinguistica (
    id          bigint  NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    catalogo_id integer NULL UNIQUE CHECK (catalogo_id >= 0),
    nombre      varchar(100) NOT NULL UNIQUE
);

CREATE TABLE web_lengua (
    id                   bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    catalogo_id          integer NULL UNIQUE CHECK (catalogo_id >= 0),
    familia_id           bigint NULL,
    nombre               varchar(100) NOT NULL,
    clave_inali          varchar(20)  NOT NULL UNIQUE,
    es_indigena          boolean      NOT NULL,
    agrupacion_linguistica varchar(150) NOT NULL,
    variante_linguistica varchar(200) NOT NULL,   -- nombre de variante del catálogo INALI
    autodenominacion     varchar(200) NOT NULL,
    estado_region        varchar(200) NOT NULL
);

-- ===========================================================================
-- CATÁLOGO MÉDICO (CIF / CIE-10)
-- ===========================================================================

CREATE TABLE web_tipodiscapacidad (
    id          bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre      varchar(100) NOT NULL UNIQUE,
    descripcion text         NOT NULL,
    clave_inegi varchar(10)  NOT NULL
);

CREATE TABLE web_discapacidad (
    id          bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tipo_id     bigint NOT NULL,
    nombre      varchar(150) NOT NULL,
    descripcion text         NOT NULL
);

CREATE TABLE web_capituloenfermedad (
    id           bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    codigo       varchar(5)   NOT NULL UNIQUE,
    nombre       varchar(200) NOT NULL,
    rango_inicio varchar(5)   NOT NULL,
    rango_fin    varchar(5)   NOT NULL
);

CREATE TABLE web_enfermedad (
    id           bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    capitulo_id  bigint NULL,
    codigo_cie10 varchar(10)  NOT NULL UNIQUE,
    nombre       varchar(300) NOT NULL,
    nombre_corto varchar(100) NOT NULL
);

-- ===========================================================================
-- OPERATIVO: EMPLEADOS Y EQUIPOS
-- ===========================================================================

CREATE TABLE web_empleado (
    id                  bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    usuario_id          integer NOT NULL UNIQUE,
    nombre              varchar(50) NOT NULL,
    apellido_paterno    varchar(50) NOT NULL,
    apellido_materno    varchar(50) NOT NULL,
    rfc                 varchar(13) NOT NULL UNIQUE,
    curp                varchar(18) NOT NULL UNIQUE,
    sexo_catalogo_id    bigint NULL,
    fecha_nacimiento    date NOT NULL,
    domicilio_id        bigint NULL,
    tipo_trabajador     varchar(20) NOT NULL,
    rol                 varchar(50) NOT NULL,
    cedula_profesional  varchar(20) NOT NULL,
    telefono            varchar(15) NOT NULL,
    fecha_registro      timestamp with time zone NOT NULL
);

CREATE TABLE web_equipomultidisciplinario (
    id                  bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre              varchar(100) NOT NULL,
    abogado_id          bigint NOT NULL,
    doctor_id           bigint NOT NULL,
    trabajador_social_id bigint NOT NULL,
    psicologo_id        bigint NOT NULL,
    coordinador_id      bigint NULL,
    fecha_creacion      timestamp with time zone NOT NULL
);

CREATE TABLE web_contactoempleado (
    id          bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    empleado_id bigint NOT NULL,
    tipo_id     bigint NOT NULL,
    valor       varchar(200) NOT NULL,
    descripcion varchar(200) NOT NULL,
    principal   boolean      NOT NULL
);

-- ===========================================================================
-- BENEFICIARIOS: TUTOR Y NNA
-- ===========================================================================

CREATE TABLE web_tutor (
    id                           bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre                       varchar(50)  NOT NULL,
    apellido_paterno             varchar(50)  NOT NULL,
    apellido_materno             varchar(50)  NOT NULL,
    sexo_catalogo_id             bigint NULL,
    fecha_nacimiento             date NULL,
    curp                         varchar(18) NULL UNIQUE,
    rfc                          varchar(13) NOT NULL,
    tipo_identificacion          varchar(20) NOT NULL,
    numero_identificacion        varchar(50) NOT NULL,
    parentesco_con_nna           varchar(30) NOT NULL,
    estado_civil                 varchar(20) NOT NULL,
    escolaridad                  varchar(30) NOT NULL,
    ocupacion                    varchar(100) NOT NULL,
    ingreso_mensual_aproximado   numeric(10,2) NULL,
    telefono_principal           varchar(15)  NOT NULL,
    telefono_alternativo         varchar(15)  NOT NULL,
    correo_electronico           varchar(254) NOT NULL,
    domicilio_id                 bigint NULL,
    observaciones                text NOT NULL,
    fecha_registro               timestamp with time zone NOT NULL,
    fecha_actualizacion          timestamp with time zone NOT NULL
);

CREATE TABLE web_nna (
    id                           bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folio_nna                    varchar(20) NULL UNIQUE,
    nombre                       varchar(50) NOT NULL,
    nombre_preferido             varchar(80) NOT NULL DEFAULT '',
    apellido_paterno             varchar(50) NOT NULL,
    apellido_materno             varchar(50) NOT NULL,
    fecha_nacimiento             date NOT NULL,
    sexo_catalogo_id             bigint NULL,
    curp                         varchar(18) NULL UNIQUE,
    escolaridad                  varchar(30) NOT NULL,
    nombre_escuela               varchar(200) NOT NULL,
    lugar_nacimiento_estado_id   bigint NULL,
    lugar_nacimiento_municipio_id bigint NULL,
    es_extranjero                boolean NOT NULL,
    pais_origen                  varchar(100) NOT NULL,
    condicion_migratoria         varchar(12)  NOT NULL,
    pais_destino                 varchar(100) NOT NULL,
    pertenece_comunidad_indigena boolean NOT NULL,
    comunidad_indigena           varchar(150) NOT NULL,
    situacion_calle              boolean NOT NULL,
    requiere_interprete          boolean NOT NULL,
    lengua_interprete            varchar(100) NOT NULL,
    domicilio_id                 bigint NULL,
    vive_con_tutor               boolean NOT NULL,
    equipo_id                    bigint NULL,
    estatus                      varchar(20) NOT NULL,
    estatus_proceso              varchar(20) NOT NULL DEFAULT 'ingreso',
    fecha_ingreso                date NOT NULL,
    fecha_egreso                 date NULL,
    registrado_por_id            bigint NULL,
    fecha_registro               timestamp with time zone NOT NULL,
    fecha_actualizacion          timestamp with time zone NOT NULL,
    observaciones_generales      text NOT NULL
);

-- Relación NNA ↔ Tutor
-- Un NNA puede cambiar de tutor a lo largo del tiempo.
-- principal=TRUE indica el tutor vigente; solo puede haber uno por NNA (UniqueConstraint parcial).
-- El registro anterior se cierra poniendo principal=FALSE y registrando fecha_fin.
CREATE TABLE web_nnatutor (
    id            bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id        bigint NOT NULL,
    tutor_id      bigint NOT NULL,
    parentesco    varchar(30) NOT NULL DEFAULT '',
    principal     boolean     NOT NULL DEFAULT FALSE,
    fecha_inicio  date NULL,
    fecha_fin     date NULL,
    observaciones text NOT NULL DEFAULT ''
    -- La unicidad "solo un tutor principal por NNA" se implementa con índice parcial (ver sección índices)
);

-- Relación NNA ↔ Equipo Multidisciplinario (historial)
-- Un NNA puede cambiar de equipo a lo largo del tiempo.
-- activo=TRUE indica el equipo vigente; solo puede haber uno por NNA (UniqueConstraint parcial).
-- El registro anterior se cierra poniendo activo=FALSE y registrando fecha_fin.
CREATE TABLE web_nnaequipo (
    id            bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id        bigint NOT NULL,
    equipo_id     bigint NOT NULL,
    fecha_inicio  date   NOT NULL,
    fecha_fin     date   NULL,
    activo        boolean NOT NULL DEFAULT TRUE,
    motivo_cambio text    NOT NULL DEFAULT ''
);

CREATE TABLE web_nacionalidadnna (
    id              bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id          bigint NOT NULL,
    nacionalidad_id bigint NOT NULL,
    principal       boolean NOT NULL
);

CREATE TABLE web_contactonna (
    id          bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id      bigint NOT NULL,
    tipo_id     bigint NOT NULL,
    valor       varchar(200) NOT NULL,
    descripcion varchar(200) NOT NULL,
    principal   boolean      NOT NULL
);

CREATE TABLE web_contactotutor (
    id          bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tutor_id    bigint NOT NULL,
    tipo_id     bigint NOT NULL,
    valor       varchar(200) NOT NULL,
    descripcion varchar(200) NOT NULL,
    principal   boolean      NOT NULL
);

CREATE TABLE web_seguimientonna (
    id                  bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id              bigint NOT NULL,
    area                varchar(20)  NOT NULL,
    registrado_por_id   bigint NULL,
    fecha               date NOT NULL,
    titulo              varchar(150) NOT NULL,
    descripcion         text NOT NULL,
    acuerdos            text NOT NULL,
    proxima_accion      text NOT NULL,
    estatus             varchar(20) NOT NULL,
    fecha_registro      timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL
);

-- ---------------------------------------------------------------------------
-- IDIOMAS
-- Los idiomas de NNA, tutores y empleados son OPCIONALES (0..N por persona).
-- No existe restricción de mínimo; una persona puede no tener idiomas registrados.
-- El campo "variante" en web_idiomanna captura la variante específica del NNA
-- como texto libre (p. ej. "Náhuatl de la Huasteca") sin necesidad de catálogo.
-- ---------------------------------------------------------------------------

CREATE TABLE web_idiomanna (
    id                   bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id               bigint NOT NULL,
    lengua_id            bigint NOT NULL,
    variante             varchar(200) NOT NULL DEFAULT '',  -- variante específica que habla el NNA
    nivel                varchar(20)  NOT NULL,
    nivel_competencia_id bigint NULL,
    modo_adquisicion_id  bigint NULL,
    es_lengua_materna    boolean NOT NULL,
    preferente           boolean NOT NULL,
    autodenominacion     varchar(200) NOT NULL
);

CREATE TABLE web_idiomatutor (
    id                   bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tutor_id             bigint NOT NULL,
    lengua_id            bigint NOT NULL,
    nivel                varchar(20)  NOT NULL,
    nivel_competencia_id bigint NULL,
    modo_adquisicion_id  bigint NULL,
    es_lengua_materna    boolean NOT NULL,
    preferente           boolean NOT NULL
);

CREATE TABLE web_idiomaempleado (
    id                   bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    empleado_id          bigint NOT NULL,
    lengua_id            bigint NOT NULL,
    nivel                varchar(20)  NOT NULL,
    nivel_competencia_id bigint NULL,
    modo_adquisicion_id  bigint NULL,
    es_lengua_materna    boolean NOT NULL,
    preferente           boolean NOT NULL
);

CREATE TABLE web_discapacidadnna (
    id                     bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id                 bigint NOT NULL,
    tipo_id                bigint NOT NULL,
    discapacidad_id        bigint NULL,
    descripcion_especifica text NOT NULL,
    -- grado_dependencia: valores permitidos leve/moderada/severa/total (o vacío)
    grado_dependencia      varchar(10) NOT NULL DEFAULT '',
    causa                  varchar(20) NOT NULL,
    certificado_medico     boolean     NOT NULL,
    observaciones          text        NOT NULL
);

CREATE TABLE web_padecimientonna (
    id                          bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id                      bigint NOT NULL,
    enfermedad_id               bigint NOT NULL,
    fecha_diagnostico           date NULL,
    diagnostico_medico          text NOT NULL DEFAULT '',
    es_cronica                  boolean NOT NULL DEFAULT false,
    bajo_tratamiento            boolean NOT NULL DEFAULT false,
    requiere_medicamento        boolean NOT NULL DEFAULT false,
    estado_tratamiento          varchar(20) NOT NULL DEFAULT 'sin_tratamiento',
    esta_controlada             boolean NOT NULL DEFAULT false,
    requiere_atencion_fundacion boolean NOT NULL DEFAULT false,
    medicamentos                text NOT NULL DEFAULT '',
    observaciones_medicas       text NOT NULL DEFAULT '',
    diagnosticado_por_id        bigint NULL
);

-- ===========================================================================
-- JURÍDICO / DOCUMENTAL (FUD)
-- ===========================================================================

CREATE TABLE web_hechovictimal (
    id                           bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id                       bigint NOT NULL UNIQUE,
    nombre_victima_directa       varchar(150) NOT NULL,
    parentesco_victima_nna       varchar(50)  NOT NULL,
    tipo_delito                  varchar(30)  NOT NULL,
    descripcion_delito           text NOT NULL,
    fecha_hecho                  date NULL,
    hora_hecho                   time NULL,
    ambito_ocurrencia            varchar(20) NOT NULL,
    lugar_hecho                  text NOT NULL,
    lugar_hecho_municipio_id     bigint NULL,
    numero_carpeta_investigacion varchar(100) NOT NULL,
    fiscalia_o_ministerio        varchar(200) NOT NULL,
    numero_expediente_judicial   varchar(100) NOT NULL,
    juzgado                      varchar(200) NOT NULL,
    estatus_juridico             varchar(30)  NOT NULL,
    hay_detenidos                boolean NOT NULL,
    datos_detenidos              text NOT NULL,
    nna_fue_testigo              boolean NOT NULL,
    nna_tambien_victima          boolean NOT NULL,
    descripcion_impacto_nna      text NOT NULL,
    derivado_por                 varchar(200) NOT NULL,
    tipo_institucion_derivadora  varchar(30)  NOT NULL,
    registrado_por_id            bigint NULL,
    fecha_registro               timestamp with time zone NOT NULL,
    fecha_actualizacion          timestamp with time zone NOT NULL,
    observaciones                text NOT NULL
);

CREATE TABLE web_documentoexpediente (
    id              bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id          bigint NOT NULL,
    tipo            varchar(30)  NOT NULL,
    nombre_archivo  varchar(255) NOT NULL,
    archivo         varchar(100) NOT NULL,
    descripcion     text NOT NULL,
    fecha_documento date NULL,
    subido_por_id   bigint NULL,
    fecha_subida    timestamp with time zone NOT NULL
);

-- ===========================================================================
-- RESTITUCIÓN DE DERECHOS (LGDNNA / Caja de Herramientas)
-- ===========================================================================

CREATE TABLE web_derecho (
    id          bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clave       varchar(6)   NOT NULL UNIQUE,
    nombre      varchar(200) NOT NULL UNIQUE,
    fundamento  varchar(200) NOT NULL,
    descripcion text         NOT NULL
);

CREATE TABLE web_planrestitucion (
    id                              bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id                          bigint NOT NULL,
    folio                           varchar(30) NOT NULL UNIQUE,
    fecha_apertura                  date NOT NULL,
    elaborado_por_id                bigint NULL,
    equipo_id                       bigint NULL,
    grado_peligro                   varchar(12) NOT NULL,
    grado_coercion                  varchar(12) NOT NULL,
    diagnostico_general             text NOT NULL,
    determinacion_interes_superior  text NOT NULL,
    estatus                         varchar(15) NOT NULL,
    vigente                         boolean NOT NULL,
    fecha_cierre                    date NULL,
    fecha_registro                  timestamp with time zone NOT NULL,
    fecha_actualizacion             timestamp with time zone NOT NULL
);

CREATE TABLE web_derechovulnerado (
    id          bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plan_id     bigint NOT NULL,
    derecho_id  bigint NOT NULL,
    grado       varchar(12) NOT NULL,
    descripcion text        NOT NULL
);

-- ===========================================================================
-- AUDITORÍA DE ACCESO
-- ===========================================================================

CREATE TABLE web_bitacoraacceso (
    id         bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    usuario_id integer NULL,
    accion     varchar(15) NOT NULL,
    modelo     varchar(80) NOT NULL,
    objeto_id  varchar(40) NOT NULL,
    nna_id     bigint NULL,
    ip         inet NULL,
    detalle    varchar(255) NOT NULL,
    fecha_hora timestamp with time zone NOT NULL
);

-- ===========================================================================
-- LLAVES FORÁNEAS
-- ===========================================================================

-- Geografía
ALTER TABLE web_municipio         ADD CONSTRAINT fk_municipio_entidad         FOREIGN KEY (entidad_id)            REFERENCES web_entidadfederativa (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_asentamiento      ADD CONSTRAINT fk_asentamiento_municipio    FOREIGN KEY (municipio_id)          REFERENCES web_municipio (id)         DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_asentamiento      ADD CONSTRAINT fk_asentamiento_tipo         FOREIGN KEY (tipo_asentamiento_id)  REFERENCES web_tipoasentamiento (id)  DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_domicilio         ADD CONSTRAINT fk_domicilio_asentamiento    FOREIGN KEY (asentamiento_id)       REFERENCES web_asentamiento (id)      DEFERRABLE INITIALLY DEFERRED;

-- Catálogos lingüísticos
ALTER TABLE web_lengua            ADD CONSTRAINT fk_lengua_familia            FOREIGN KEY (familia_id)            REFERENCES web_familialinguistica (id) DEFERRABLE INITIALLY DEFERRED;

-- Catálogos médicos
ALTER TABLE web_discapacidad      ADD CONSTRAINT fk_discapacidad_tipo         FOREIGN KEY (tipo_id)               REFERENCES web_tipodiscapacidad (id)  DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_enfermedad        ADD CONSTRAINT fk_enfermedad_capitulo       FOREIGN KEY (capitulo_id)           REFERENCES web_capituloenfermedad (id) DEFERRABLE INITIALLY DEFERRED;

-- Empleados
ALTER TABLE web_empleado          ADD CONSTRAINT fk_empleado_usuario          FOREIGN KEY (usuario_id)            REFERENCES auth_user (id)             DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_empleado          ADD CONSTRAINT fk_empleado_sexo             FOREIGN KEY (sexo_catalogo_id)      REFERENCES web_sexo (id)              DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_empleado          ADD CONSTRAINT fk_empleado_domicilio        FOREIGN KEY (domicilio_id)          REFERENCES web_domicilio (id)         DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_equipomultidisciplinario ADD CONSTRAINT fk_equipo_abogado     FOREIGN KEY (abogado_id)            REFERENCES web_empleado (id)          DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_equipomultidisciplinario ADD CONSTRAINT fk_equipo_doctor      FOREIGN KEY (doctor_id)             REFERENCES web_empleado (id)          DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_equipomultidisciplinario ADD CONSTRAINT fk_equipo_ts          FOREIGN KEY (trabajador_social_id)  REFERENCES web_empleado (id)          DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_equipomultidisciplinario ADD CONSTRAINT fk_equipo_psicologo   FOREIGN KEY (psicologo_id)          REFERENCES web_empleado (id)          DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_equipomultidisciplinario ADD CONSTRAINT fk_equipo_coordinador FOREIGN KEY (coordinador_id)        REFERENCES web_empleado (id)          DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_contactoempleado  ADD CONSTRAINT fk_contactoempleado_empleado FOREIGN KEY (empleado_id)           REFERENCES web_empleado (id)          DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_contactoempleado  ADD CONSTRAINT fk_contactoempleado_tipo     FOREIGN KEY (tipo_id)               REFERENCES web_tipocontacto (id)      DEFERRABLE INITIALLY DEFERRED;

-- Tutor
ALTER TABLE web_tutor             ADD CONSTRAINT fk_tutor_sexo               FOREIGN KEY (sexo_catalogo_id)      REFERENCES web_sexo (id)              DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_tutor             ADD CONSTRAINT fk_tutor_domicilio           FOREIGN KEY (domicilio_id)          REFERENCES web_domicilio (id)         DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_contactotutor     ADD CONSTRAINT fk_contactotutor_tutor       FOREIGN KEY (tutor_id)              REFERENCES web_tutor (id)             DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_contactotutor     ADD CONSTRAINT fk_contactotutor_tipo        FOREIGN KEY (tipo_id)               REFERENCES web_tipocontacto (id)      DEFERRABLE INITIALLY DEFERRED;

-- NNA
ALTER TABLE web_nna               ADD CONSTRAINT fk_nna_sexo                 FOREIGN KEY (sexo_catalogo_id)             REFERENCES web_sexo (id)                       DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nna               ADD CONSTRAINT fk_nna_estado               FOREIGN KEY (lugar_nacimiento_estado_id)   REFERENCES web_entidadfederativa (id)           DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nna               ADD CONSTRAINT fk_nna_municipio            FOREIGN KEY (lugar_nacimiento_municipio_id) REFERENCES web_municipio (id)                  DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nna               ADD CONSTRAINT fk_nna_domicilio            FOREIGN KEY (domicilio_id)                 REFERENCES web_domicilio (id)                   DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nna               ADD CONSTRAINT fk_nna_equipo               FOREIGN KEY (equipo_id)                    REFERENCES web_equipomultidisciplinario (id)     DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nna               ADD CONSTRAINT fk_nna_registrado_por       FOREIGN KEY (registrado_por_id)            REFERENCES web_empleado (id)                    DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nnatutor          ADD CONSTRAINT fk_nnatutor_nna             FOREIGN KEY (nna_id)               REFERENCES web_nna (id)               DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nnatutor          ADD CONSTRAINT fk_nnatutor_tutor           FOREIGN KEY (tutor_id)             REFERENCES web_tutor (id)             DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nnaequipo         ADD CONSTRAINT fk_nnaequipo_nna            FOREIGN KEY (nna_id)               REFERENCES web_nna (id)               DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nnaequipo         ADD CONSTRAINT fk_nnaequipo_equipo         FOREIGN KEY (equipo_id)            REFERENCES web_equipomultidisciplinario (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nacionalidadnna   ADD CONSTRAINT fk_nacionalidadnna_nna      FOREIGN KEY (nna_id)               REFERENCES web_nna (id)               DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nacionalidadnna   ADD CONSTRAINT fk_nacionalidadnna_nac      FOREIGN KEY (nacionalidad_id)      REFERENCES web_nacionalidad (id)      DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_contactonna       ADD CONSTRAINT fk_contactonna_nna          FOREIGN KEY (nna_id)               REFERENCES web_nna (id)               DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_contactonna       ADD CONSTRAINT fk_contactonna_tipo         FOREIGN KEY (tipo_id)              REFERENCES web_tipocontacto (id)      DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_seguimientonna    ADD CONSTRAINT fk_seguimientonna_nna       FOREIGN KEY (nna_id)               REFERENCES web_nna (id)               DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_seguimientonna    ADD CONSTRAINT fk_seguimientonna_empleado  FOREIGN KEY (registrado_por_id)    REFERENCES web_empleado (id)          DEFERRABLE INITIALLY DEFERRED;

-- Idiomas (0..N por persona; ninguna fila = sin idiomas registrados)
ALTER TABLE web_idiomanna         ADD CONSTRAINT fk_idiomanna_nna            FOREIGN KEY (nna_id)               REFERENCES web_nna (id)                    DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_idiomanna         ADD CONSTRAINT fk_idiomanna_lengua         FOREIGN KEY (lengua_id)            REFERENCES web_lengua (id)                 DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_idiomanna         ADD CONSTRAINT fk_idiomanna_nivel          FOREIGN KEY (nivel_competencia_id) REFERENCES web_nivelcompetenciaoral (id)    DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_idiomanna         ADD CONSTRAINT fk_idiomanna_modo           FOREIGN KEY (modo_adquisicion_id)  REFERENCES web_modoadquisicionlengua (id)   DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_idiomatutor       ADD CONSTRAINT fk_idiomatutor_tutor        FOREIGN KEY (tutor_id)             REFERENCES web_tutor (id)                  DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_idiomatutor       ADD CONSTRAINT fk_idiomatutor_lengua       FOREIGN KEY (lengua_id)            REFERENCES web_lengua (id)                 DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_idiomatutor       ADD CONSTRAINT fk_idiomatutor_nivel        FOREIGN KEY (nivel_competencia_id) REFERENCES web_nivelcompetenciaoral (id)    DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_idiomatutor       ADD CONSTRAINT fk_idiomatutor_modo         FOREIGN KEY (modo_adquisicion_id)  REFERENCES web_modoadquisicionlengua (id)   DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_idiomaempleado    ADD CONSTRAINT fk_idiomaempleado_empleado  FOREIGN KEY (empleado_id)          REFERENCES web_empleado (id)               DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_idiomaempleado    ADD CONSTRAINT fk_idiomaempleado_lengua    FOREIGN KEY (lengua_id)            REFERENCES web_lengua (id)                 DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_idiomaempleado    ADD CONSTRAINT fk_idiomaempleado_nivel     FOREIGN KEY (nivel_competencia_id) REFERENCES web_nivelcompetenciaoral (id)    DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_idiomaempleado    ADD CONSTRAINT fk_idiomaempleado_modo      FOREIGN KEY (modo_adquisicion_id)  REFERENCES web_modoadquisicionlengua (id)   DEFERRABLE INITIALLY DEFERRED;

-- Discapacidades y padecimientos
ALTER TABLE web_discapacidadnna   ADD CONSTRAINT fk_discapacidadnna_nna      FOREIGN KEY (nna_id)               REFERENCES web_nna (id)               DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_discapacidadnna   ADD CONSTRAINT fk_discapacidadnna_tipo     FOREIGN KEY (tipo_id)              REFERENCES web_tipodiscapacidad (id)  DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_discapacidadnna   ADD CONSTRAINT fk_discapacidadnna_disc     FOREIGN KEY (discapacidad_id)      REFERENCES web_discapacidad (id)      DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_padecimientonna   ADD CONSTRAINT fk_padecimientonna_nna      FOREIGN KEY (nna_id)               REFERENCES web_nna (id)               DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_padecimientonna   ADD CONSTRAINT fk_padecimientonna_enf      FOREIGN KEY (enfermedad_id)        REFERENCES web_enfermedad (id)        DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_padecimientonna   ADD CONSTRAINT fk_padecimientonna_doctor   FOREIGN KEY (diagnosticado_por_id) REFERENCES web_empleado (id)          DEFERRABLE INITIALLY DEFERRED;

-- Jurídico
ALTER TABLE web_hechovictimal     ADD CONSTRAINT fk_hechovictimal_nna        FOREIGN KEY (nna_id)               REFERENCES web_nna (id)               DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_hechovictimal     ADD CONSTRAINT fk_hechovictimal_municipio  FOREIGN KEY (lugar_hecho_municipio_id) REFERENCES web_municipio (id)    DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_hechovictimal     ADD CONSTRAINT fk_hechovictimal_empleado   FOREIGN KEY (registrado_por_id)    REFERENCES web_empleado (id)          DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_documentoexpediente ADD CONSTRAINT fk_documento_nna          FOREIGN KEY (nna_id)               REFERENCES web_nna (id)               DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_documentoexpediente ADD CONSTRAINT fk_documento_subido_por   FOREIGN KEY (subido_por_id)        REFERENCES web_empleado (id)          DEFERRABLE INITIALLY DEFERRED;

-- Plan de restitución
ALTER TABLE web_planrestitucion   ADD CONSTRAINT fk_plan_nna                 FOREIGN KEY (nna_id)               REFERENCES web_nna (id)                      DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_planrestitucion   ADD CONSTRAINT fk_plan_elaborado_por       FOREIGN KEY (elaborado_por_id)     REFERENCES web_empleado (id)                  DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_planrestitucion   ADD CONSTRAINT fk_plan_equipo              FOREIGN KEY (equipo_id)            REFERENCES web_equipomultidisciplinario (id)   DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_derechovulnerado  ADD CONSTRAINT fk_derechovulnerado_plan    FOREIGN KEY (plan_id)              REFERENCES web_planrestitucion (id)            DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_derechovulnerado  ADD CONSTRAINT fk_derechovulnerado_derecho FOREIGN KEY (derecho_id)           REFERENCES web_derecho (id)                    DEFERRABLE INITIALLY DEFERRED;

-- Auditoría
ALTER TABLE web_bitacoraacceso    ADD CONSTRAINT fk_bitacora_usuario         FOREIGN KEY (usuario_id)           REFERENCES auth_user (id)             DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_bitacoraacceso    ADD CONSTRAINT fk_bitacora_nna             FOREIGN KEY (nna_id)               REFERENCES web_nna (id)               DEFERRABLE INITIALLY DEFERRED;

-- ===========================================================================
-- TRIGGERS: auto-actualización de fecha_actualizacion
-- ===========================================================================
CREATE TRIGGER trg_web_tutor_fecha_actualizacion
    BEFORE UPDATE ON web_tutor FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();
CREATE TRIGGER trg_web_nna_fecha_actualizacion
    BEFORE UPDATE ON web_nna FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();
CREATE TRIGGER trg_web_seguimientonna_fecha_actualizacion
    BEFORE UPDATE ON web_seguimientonna FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();
CREATE TRIGGER trg_web_hechovictimal_fecha_actualizacion
    BEFORE UPDATE ON web_hechovictimal FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();
CREATE TRIGGER trg_web_planrestitucion_fecha_actualizacion
    BEFORE UPDATE ON web_planrestitucion FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

-- ===========================================================================
-- ÍNDICES
-- ===========================================================================

-- Geografía
CREATE INDEX idx_municipio_entidad          ON web_municipio (entidad_id);
CREATE INDEX idx_asentamiento_municipio     ON web_asentamiento (municipio_id);
CREATE INDEX idx_asentamiento_tipo          ON web_asentamiento (tipo_asentamiento_id);
CREATE INDEX idx_asentamiento_cp            ON web_asentamiento (codigo_postal);
CREATE INDEX idx_asentamiento_cp_like       ON web_asentamiento (codigo_postal varchar_pattern_ops);
CREATE INDEX idx_domicilio_asentamiento     ON web_domicilio (asentamiento_id);

-- Catálogos base (claves de texto para búsquedas LIKE)
CREATE INDEX idx_sexo_clave_like            ON web_sexo (clave varchar_pattern_ops);
CREATE INDEX idx_sexo_nombre_like           ON web_sexo (nombre varchar_pattern_ops);
CREATE INDEX idx_nacionalidad_clave_like    ON web_nacionalidad (clave varchar_pattern_ops);
CREATE INDEX idx_nacionalidad_nombre_like   ON web_nacionalidad (nombre varchar_pattern_ops);
CREATE INDEX idx_tipocontacto_clave_like    ON web_tipocontacto (clave varchar_pattern_ops);
CREATE INDEX idx_tipocontacto_nombre_like   ON web_tipocontacto (nombre varchar_pattern_ops);
CREATE INDEX idx_nivelcomp_clave_like       ON web_nivelcompetenciaoral (clave varchar_pattern_ops);
CREATE INDEX idx_nivelcomp_nombre_like      ON web_nivelcompetenciaoral (nombre varchar_pattern_ops);
CREATE INDEX idx_modoadq_clave_like         ON web_modoadquisicionlengua (clave varchar_pattern_ops);

-- Catálogo lingüístico
CREATE INDEX idx_familialinguistica_nombre  ON web_familialinguistica (nombre varchar_pattern_ops);
CREATE INDEX idx_lengua_familia             ON web_lengua (familia_id);
CREATE INDEX idx_lengua_clave_inali_like    ON web_lengua (clave_inali varchar_pattern_ops);

-- Catálogo médico
CREATE INDEX idx_tipodiscapacidad_nombre    ON web_tipodiscapacidad (nombre varchar_pattern_ops);
CREATE INDEX idx_discapacidad_tipo          ON web_discapacidad (tipo_id);
CREATE INDEX idx_capitulo_codigo_like       ON web_capituloenfermedad (codigo varchar_pattern_ops);
CREATE INDEX idx_enfermedad_capitulo        ON web_enfermedad (capitulo_id);
CREATE INDEX idx_enfermedad_cie10_like      ON web_enfermedad (codigo_cie10 varchar_pattern_ops);

-- Empleados
CREATE INDEX idx_empleado_rfc_like          ON web_empleado (rfc varchar_pattern_ops);
CREATE INDEX idx_empleado_curp_like         ON web_empleado (curp varchar_pattern_ops);
CREATE INDEX idx_empleado_sexo              ON web_empleado (sexo_catalogo_id);
CREATE INDEX idx_empleado_domicilio         ON web_empleado (domicilio_id);
CREATE INDEX idx_equipo_abogado             ON web_equipomultidisciplinario (abogado_id);
CREATE INDEX idx_equipo_doctor              ON web_equipomultidisciplinario (doctor_id);
CREATE INDEX idx_equipo_ts                  ON web_equipomultidisciplinario (trabajador_social_id);
CREATE INDEX idx_equipo_psicologo           ON web_equipomultidisciplinario (psicologo_id);
CREATE INDEX idx_equipo_coordinador         ON web_equipomultidisciplinario (coordinador_id);
CREATE INDEX idx_contactoempleado_empleado  ON web_contactoempleado (empleado_id);
CREATE INDEX idx_contactoempleado_tipo      ON web_contactoempleado (tipo_id);

-- Tutor
CREATE INDEX idx_tutor_sexo                 ON web_tutor (sexo_catalogo_id);
CREATE INDEX idx_tutor_curp_like            ON web_tutor (curp varchar_pattern_ops);
CREATE INDEX idx_tutor_domicilio            ON web_tutor (domicilio_id);
CREATE INDEX idx_contactotutor_tutor        ON web_contactotutor (tutor_id);
CREATE INDEX idx_contactotutor_tipo         ON web_contactotutor (tipo_id);

-- NNA
CREATE INDEX idx_nna_folio_like             ON web_nna (folio_nna varchar_pattern_ops);
CREATE INDEX idx_nna_sexo                   ON web_nna (sexo_catalogo_id);
CREATE INDEX idx_nna_curp_like              ON web_nna (curp varchar_pattern_ops);
CREATE INDEX idx_nna_estado                 ON web_nna (lugar_nacimiento_estado_id);
CREATE INDEX idx_nna_municipio              ON web_nna (lugar_nacimiento_municipio_id);
CREATE INDEX idx_nna_domicilio              ON web_nna (domicilio_id);
CREATE INDEX idx_nna_equipo                 ON web_nna (equipo_id);
CREATE INDEX idx_nna_registrado_por         ON web_nna (registrado_por_id);
CREATE INDEX idx_nnatutor_nna               ON web_nnatutor (nna_id);
CREATE INDEX idx_nnatutor_tutor             ON web_nnatutor (tutor_id);
CREATE UNIQUE INDEX uniq_nnatutor_principal ON web_nnatutor (nna_id) WHERE principal = TRUE;
CREATE INDEX idx_nnaequipo_nna              ON web_nnaequipo (nna_id);
CREATE INDEX idx_nnaequipo_equipo           ON web_nnaequipo (equipo_id);
CREATE UNIQUE INDEX uniq_nnaequipo_activo   ON web_nnaequipo (nna_id) WHERE activo = TRUE;
CREATE INDEX idx_nacionalidadnna_nna        ON web_nacionalidadnna (nna_id);
CREATE INDEX idx_nacionalidadnna_nac        ON web_nacionalidadnna (nacionalidad_id);
CREATE INDEX idx_contactonna_nna            ON web_contactonna (nna_id);
CREATE INDEX idx_contactonna_tipo           ON web_contactonna (tipo_id);
CREATE INDEX idx_seguimientonna_nna         ON web_seguimientonna (nna_id);
CREATE INDEX idx_seguimientonna_empleado    ON web_seguimientonna (registrado_por_id);

-- Idiomas
CREATE INDEX idx_idiomanna_nna              ON web_idiomanna (nna_id);
CREATE INDEX idx_idiomanna_lengua           ON web_idiomanna (lengua_id);
CREATE INDEX idx_idiomanna_nivel            ON web_idiomanna (nivel_competencia_id);
CREATE INDEX idx_idiomanna_modo             ON web_idiomanna (modo_adquisicion_id);
CREATE INDEX idx_idiomatutor_tutor          ON web_idiomatutor (tutor_id);
CREATE INDEX idx_idiomatutor_lengua         ON web_idiomatutor (lengua_id);
CREATE INDEX idx_idiomatutor_nivel          ON web_idiomatutor (nivel_competencia_id);
CREATE INDEX idx_idiomatutor_modo           ON web_idiomatutor (modo_adquisicion_id);
CREATE INDEX idx_idiomaempleado_empleado    ON web_idiomaempleado (empleado_id);
CREATE INDEX idx_idiomaempleado_lengua      ON web_idiomaempleado (lengua_id);
CREATE INDEX idx_idiomaempleado_nivel       ON web_idiomaempleado (nivel_competencia_id);
CREATE INDEX idx_idiomaempleado_modo        ON web_idiomaempleado (modo_adquisicion_id);

-- Discapacidades y padecimientos
CREATE INDEX idx_discapacidadnna_nna        ON web_discapacidadnna (nna_id);
CREATE INDEX idx_discapacidadnna_tipo       ON web_discapacidadnna (tipo_id);
CREATE INDEX idx_discapacidadnna_disc       ON web_discapacidadnna (discapacidad_id);
CREATE INDEX idx_padecimientonna_nna        ON web_padecimientonna (nna_id);
CREATE INDEX idx_padecimientonna_enf        ON web_padecimientonna (enfermedad_id);
CREATE INDEX idx_padecimientonna_doctor     ON web_padecimientonna (diagnosticado_por_id);

-- Jurídico
CREATE INDEX idx_hechovictimal_municipio    ON web_hechovictimal (lugar_hecho_municipio_id);
CREATE INDEX idx_hechovictimal_empleado     ON web_hechovictimal (registrado_por_id);
CREATE INDEX idx_documento_nna              ON web_documentoexpediente (nna_id);
CREATE INDEX idx_documento_subido_por       ON web_documentoexpediente (subido_por_id);

-- Derechos y plan
CREATE INDEX idx_derecho_clave_like         ON web_derecho (clave varchar_pattern_ops);
CREATE INDEX idx_derecho_nombre_like        ON web_derecho (nombre varchar_pattern_ops);
CREATE INDEX idx_plan_nna                   ON web_planrestitucion (nna_id);
CREATE INDEX idx_plan_folio_like            ON web_planrestitucion (folio varchar_pattern_ops);
CREATE INDEX idx_plan_elaborado_por         ON web_planrestitucion (elaborado_por_id);
CREATE INDEX idx_plan_equipo                ON web_planrestitucion (equipo_id);
CREATE INDEX idx_derechovulnerado_plan      ON web_derechovulnerado (plan_id);
CREATE INDEX idx_derechovulnerado_derecho   ON web_derechovulnerado (derecho_id);

-- Bitácora
CREATE INDEX idx_bitacora_usuario           ON web_bitacoraacceso (usuario_id);
CREATE INDEX idx_bitacora_nna               ON web_bitacoraacceso (nna_id);
CREATE INDEX idx_bitacora_fecha             ON web_bitacoraacceso (fecha_hora);

-- ===========================================================================
-- RESTRICCIONES ÚNICAS
-- ===========================================================================

ALTER TABLE web_municipio          ADD CONSTRAINT uniq_municipio_entidad_clave    UNIQUE (entidad_id, clave);
ALTER TABLE web_discapacidad       ADD CONSTRAINT uniq_discapacidad_tipo_nombre   UNIQUE (tipo_id, nombre);
ALTER TABLE web_nnatutor           ADD CONSTRAINT uniq_nnatutor_par               UNIQUE (nna_id, tutor_id);
ALTER TABLE web_nacionalidadnna    ADD CONSTRAINT uniq_nacionalidadnna            UNIQUE (nna_id, nacionalidad_id);
ALTER TABLE web_contactonna        ADD CONSTRAINT uniq_contactonna                UNIQUE (nna_id, tipo_id, valor);
ALTER TABLE web_contactotutor      ADD CONSTRAINT uniq_contactotutor              UNIQUE (tutor_id, tipo_id, valor);
ALTER TABLE web_contactoempleado   ADD CONSTRAINT uniq_contactoempleado           UNIQUE (empleado_id, tipo_id, valor);

-- Un NNA no puede tener la misma lengua registrada dos veces
ALTER TABLE web_idiomanna          ADD CONSTRAINT uniq_idiomanna_nna_lengua       UNIQUE (nna_id, lengua_id);
-- Tutor/empleado tampoco (0 o N lenguas, pero sin duplicados)
ALTER TABLE web_idiomatutor        ADD CONSTRAINT uniq_idiomatutor_tutor_lengua   UNIQUE (tutor_id, lengua_id);
ALTER TABLE web_idiomaempleado     ADD CONSTRAINT uniq_idiomaempleado_emp_lengua  UNIQUE (empleado_id, lengua_id);

ALTER TABLE web_discapacidadnna    ADD CONSTRAINT uniq_discapacidadnna            UNIQUE (nna_id, tipo_id, descripcion_especifica);
ALTER TABLE web_padecimientonna    ADD CONSTRAINT uniq_padecimientonna            UNIQUE (nna_id, enfermedad_id);
ALTER TABLE web_derechovulnerado   ADD CONSTRAINT uniq_derechovulnerado           UNIQUE (plan_id, derecho_id);

-- Solo un tutor principal por NNA
CREATE UNIQUE INDEX uniq_tutor_principal_por_nna ON web_nnatutor (nna_id) WHERE principal;
-- Solo un plan vigente por NNA
CREATE UNIQUE INDEX uniq_plan_vigente_por_nna    ON web_planrestitucion (nna_id) WHERE vigente;

COMMIT;
