-- ===========================================================================
-- SIGA-NNH — Esquema NORMALIZADO (hasta 5FN) para PostgreSQL  ·  base: nnabd
-- Versión revisada por diseño. Cambios respecto a schema_postgres.sql:
--   1) Eliminada la columna 'sexo' (char) de empleado/tutor/nna: el sexo queda
--      solo como FK a web_sexo (sexo_catalogo_id). Evita el riesgo de que
--      sexo='M' y sexo_catalogo apunten a 'Femenino' (anomalía de actualización).
--   2) Eliminada la columna 'grado_dependencia' (char) de discapacidad_nna:
--      se conserva la FK grado_dependencia_catalogo_id -> web_gradodependencia.
--   3) Eliminada la FK 'tutor_id' de web_nna: el tutor principal se obtiene de
--      web_nnatutor (principal=true, con UNIQUE parcial). Se elimina así la
--      doble representación del mismo hecho (NNA–Tutor).
--
-- Resultado: sin atributos redundantes; 1FN, 2FN, 3FN, BCNF, 4FN y 5FN.
-- ===========================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS auth_user (
    id           SERIAL       PRIMARY KEY,
    password     varchar(128) NOT NULL,
    last_login   timestamp with time zone NULL,
    is_superuser boolean      NOT NULL DEFAULT false,
    username     varchar(150) NOT NULL UNIQUE,
    first_name   varchar(150) NOT NULL DEFAULT '',
    last_name    varchar(150) NOT NULL DEFAULT '',
    email        varchar(254) NOT NULL DEFAULT '',
    is_staff     boolean      NOT NULL DEFAULT false,
    is_active    boolean      NOT NULL DEFAULT true,
    date_joined  timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION set_fecha_actualizacion()
RETURNS TRIGGER AS $$
BEGIN
    NEW.fecha_actualizacion = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ===========================================================================
-- TABLAS
-- ===========================================================================

-- ------------------------------------------------------------------------
-- CATÁLOGO GEOGRÁFICO (SEPOMEX)
-- ------------------------------------------------------------------------

CREATE TABLE web_entidadfederativa (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clave varchar(2) NOT NULL UNIQUE,
    nombre varchar(100) NOT NULL,
    abreviatura varchar(10) NOT NULL
);

CREATE TABLE web_municipio (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    entidad_id bigint NOT NULL,
    clave varchar(5) NOT NULL,
    nombre varchar(150) NOT NULL
);

CREATE TABLE web_tipoasentamiento (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(80) NOT NULL UNIQUE
);

CREATE TABLE web_asentamiento (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    municipio_id bigint NOT NULL,
    tipo_asentamiento_id bigint NULL,
    nombre varchar(200) NOT NULL,
    codigo_postal varchar(5) NOT NULL,
    ciudad varchar(150) NOT NULL,
    CONSTRAINT uniq_asentamiento_municipio_cp_nombre UNIQUE (municipio_id, codigo_postal, nombre)
);

CREATE TABLE web_domicilio (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    asentamiento_id bigint NOT NULL,
    calle varchar(200) NOT NULL,
    numero_exterior varchar(20) NOT NULL,
    numero_interior varchar(20) NOT NULL,
    referencias text NOT NULL
);

-- ------------------------------------------------------------------------
-- CATÁLOGOS BASE
-- ------------------------------------------------------------------------

CREATE TABLE web_sexo (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clave varchar(3) NOT NULL UNIQUE,
    nombre varchar(80) NOT NULL UNIQUE,
    descripcion text NOT NULL
);

CREATE TABLE web_nacionalidad (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clave varchar(3) NOT NULL UNIQUE,
    nombre varchar(100) NOT NULL UNIQUE,
    descripcion text NOT NULL
);

CREATE TABLE web_tipocontacto (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clave varchar(30) NOT NULL UNIQUE,
    nombre varchar(100) NOT NULL UNIQUE,
    descripcion text NOT NULL
);

CREATE TABLE web_nivelcompetenciaoral (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clave varchar(30) NOT NULL UNIQUE,
    nombre varchar(100) NOT NULL UNIQUE,
    significado text NOT NULL,
    puede_declarar boolean NOT NULL,
    requiere_interprete boolean NOT NULL
);

CREATE TABLE web_modoadquisicionlengua (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clave varchar(30) NOT NULL UNIQUE,
    categoria varchar(100) NOT NULL,
    descripcion text NOT NULL,
    contexto text NOT NULL
);

CREATE TABLE web_gradodependencia (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clave varchar(30) NOT NULL UNIQUE,
    nombre varchar(100) NOT NULL UNIQUE,
    descripcion text NOT NULL
);

-- ------------------------------------------------------------------------
-- CATÁLOGO LINGÜÍSTICO (INALI)
-- ------------------------------------------------------------------------

CREATE TABLE web_familialinguistica (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    catalogo_id integer NULL UNIQUE CHECK (catalogo_id >= 0),
    nombre varchar(100) NOT NULL UNIQUE
);

CREATE TABLE web_lengua (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    catalogo_id integer NULL UNIQUE CHECK (catalogo_id >= 0),
    familia_id bigint NULL,
    nombre varchar(100) NOT NULL,
    clave_inali varchar(20) NOT NULL UNIQUE,
    es_indigena boolean NOT NULL,
    agrupacion_linguistica varchar(150) NOT NULL,
    variante_linguistica varchar(200) NOT NULL,
    autodenominacion varchar(200) NOT NULL,
    estado_region varchar(200) NOT NULL
);

CREATE TABLE web_variantelinguistica (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    lengua_id bigint NOT NULL,
    nombre varchar(150) NOT NULL,
    clave_inali varchar(20) NOT NULL
);

-- ------------------------------------------------------------------------
-- CATÁLOGO MÉDICO (CIF / CIE-10)
-- ------------------------------------------------------------------------

CREATE TABLE web_tipodiscapacidad (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(100) NOT NULL UNIQUE,
    descripcion text NOT NULL,
    clave_inegi varchar(10) NOT NULL
);

CREATE TABLE web_discapacidad (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tipo_id bigint NOT NULL,
    nombre varchar(150) NOT NULL,
    descripcion text NOT NULL
);

CREATE TABLE web_capituloenfermedad (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    codigo varchar(5) NOT NULL UNIQUE,
    nombre varchar(200) NOT NULL,
    rango_inicio varchar(5) NOT NULL,
    rango_fin varchar(5) NOT NULL
);

CREATE TABLE web_enfermedad (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    capitulo_id bigint NULL,
    codigo_cie10 varchar(10) NOT NULL UNIQUE,
    nombre varchar(300) NOT NULL,
    nombre_corto varchar(100) NOT NULL
);

-- ------------------------------------------------------------------------
-- OPERATIVO: EMPLEADOS Y EQUIPOS
-- ------------------------------------------------------------------------

CREATE TABLE web_empleado (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    usuario_id integer NOT NULL UNIQUE,
    nombre varchar(50) NOT NULL,
    apellido_paterno varchar(50) NOT NULL,
    apellido_materno varchar(50) NOT NULL,
    rfc varchar(13) NOT NULL UNIQUE,
    curp varchar(18) NOT NULL UNIQUE,
    sexo_catalogo_id bigint NULL,
    fecha_nacimiento date NOT NULL,
    domicilio_id bigint NULL,
    tipo_trabajador varchar(20) NOT NULL,
    rol varchar(50) NOT NULL,
    cedula_profesional varchar(20) NOT NULL,
    telefono varchar(15) NOT NULL,
    fecha_registro timestamp with time zone NOT NULL
);

CREATE TABLE web_equipomultidisciplinario (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(100) NOT NULL,
    abogado_id bigint NOT NULL,
    doctor_id bigint NOT NULL,
    trabajador_social_id bigint NOT NULL,
    psicologo_id bigint NOT NULL,
    coordinador_id bigint NULL,
    fecha_creacion timestamp with time zone NOT NULL
);

CREATE TABLE web_contactoempleado (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    empleado_id bigint NOT NULL,
    tipo_id bigint NOT NULL,
    valor varchar(200) NOT NULL,
    descripcion varchar(200) NOT NULL,
    principal boolean NOT NULL
);

-- ------------------------------------------------------------------------
-- BENEFICIARIOS: TUTOR Y NNA
-- ------------------------------------------------------------------------

CREATE TABLE web_tutor (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(50) NOT NULL,
    apellido_paterno varchar(50) NOT NULL,
    apellido_materno varchar(50) NOT NULL,
    sexo_catalogo_id bigint NULL,
    fecha_nacimiento date NULL,
    curp varchar(18) NULL UNIQUE,
    rfc varchar(13) NOT NULL,
    tipo_identificacion varchar(20) NOT NULL,
    numero_identificacion varchar(50) NOT NULL,
    parentesco_con_nna varchar(30) NOT NULL,
    estado_civil varchar(20) NOT NULL,
    escolaridad varchar(30) NOT NULL,
    ocupacion varchar(100) NOT NULL,
    ingreso_mensual_aproximado numeric(10, 2) NULL,
    telefono_principal varchar(15) NOT NULL,
    telefono_alternativo varchar(15) NOT NULL,
    correo_electronico varchar(254) NOT NULL,
    domicilio_id bigint NULL,
    observaciones text NOT NULL,
    fecha_registro timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL
);

CREATE TABLE web_nna (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folio_nna varchar(20) NULL UNIQUE,
    nombre varchar(50) NOT NULL,
    apellido_paterno varchar(50) NOT NULL,
    apellido_materno varchar(50) NOT NULL,
    fecha_nacimiento date NOT NULL,
    sexo_catalogo_id bigint NULL,
    curp varchar(18) NULL UNIQUE,
    escolaridad varchar(30) NOT NULL,
    nombre_escuela varchar(200) NOT NULL,
    lugar_nacimiento_estado_id bigint NULL,
    lugar_nacimiento_municipio_id bigint NULL,
    es_extranjero boolean NOT NULL,
    pais_origen varchar(100) NOT NULL,
    condicion_migratoria varchar(12) NOT NULL,
    pais_destino varchar(100) NOT NULL,
    pertenece_comunidad_indigena boolean NOT NULL,
    comunidad_indigena varchar(150) NOT NULL,
    situacion_calle boolean NOT NULL,
    requiere_interprete boolean NOT NULL,
    lengua_interprete varchar(100) NOT NULL,
    domicilio_id bigint NULL,
    vive_con_tutor boolean NOT NULL,
    equipo_id bigint NULL,
    estatus varchar(20) NOT NULL,
    fecha_ingreso date NOT NULL,
    fecha_egreso date NULL,
    registrado_por_id bigint NULL,
    fecha_registro timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    observaciones_generales text NOT NULL
);

CREATE TABLE web_nnatutor (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id bigint NOT NULL,
    tutor_id bigint NOT NULL,
    parentesco varchar(30) NOT NULL,
    principal boolean NOT NULL,
    fecha_inicio date NULL,
    fecha_fin date NULL,
    observaciones text NOT NULL
);

CREATE TABLE web_nacionalidadnna (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id bigint NOT NULL,
    nacionalidad_id bigint NOT NULL,
    principal boolean NOT NULL
);

CREATE TABLE web_contactonna (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id bigint NOT NULL,
    tipo_id bigint NOT NULL,
    valor varchar(200) NOT NULL,
    descripcion varchar(200) NOT NULL,
    principal boolean NOT NULL
);

CREATE TABLE web_contactotutor (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tutor_id bigint NOT NULL,
    tipo_id bigint NOT NULL,
    valor varchar(200) NOT NULL,
    descripcion varchar(200) NOT NULL,
    principal boolean NOT NULL
);

CREATE TABLE web_seguimientonna (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id bigint NOT NULL,
    area varchar(20) NOT NULL,
    registrado_por_id bigint NULL,
    fecha date NOT NULL,
    titulo varchar(150) NOT NULL,
    descripcion text NOT NULL,
    acuerdos text NOT NULL,
    proxima_accion text NOT NULL,
    estatus varchar(20) NOT NULL,
    fecha_registro timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL
);

CREATE TABLE web_idiomanna (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id bigint NOT NULL,
    lengua_id bigint NOT NULL,
    variante_id bigint NULL,
    nivel varchar(20) NOT NULL,
    nivel_competencia_id bigint NULL,
    modo_adquisicion_id bigint NULL,
    es_lengua_materna boolean NOT NULL,
    preferente boolean NOT NULL,
    autodenominacion varchar(200) NOT NULL
);

CREATE TABLE web_discapacidadnna (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id bigint NOT NULL,
    tipo_id bigint NOT NULL,
    discapacidad_id bigint NULL,
    descripcion_especifica text NOT NULL,
    grado_dependencia_catalogo_id bigint NULL,
    causa varchar(20) NOT NULL,
    certificado_medico boolean NOT NULL,
    observaciones text NOT NULL
);

CREATE TABLE web_padecimientonna (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id bigint NOT NULL,
    enfermedad_id bigint NOT NULL,
    fecha_diagnostico date NULL,
    es_cronica boolean NOT NULL,
    esta_controlada boolean NOT NULL,
    requiere_atencion_fundacion boolean NOT NULL,
    medicamentos text NOT NULL,
    observaciones_medicas text NOT NULL
);

-- ------------------------------------------------------------------------
-- JURÍDICO / DOCUMENTAL (FUD)
-- ------------------------------------------------------------------------

CREATE TABLE web_hechovictimal (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id bigint NOT NULL UNIQUE,
    nombre_victima_directa varchar(150) NOT NULL,
    parentesco_victima_nna varchar(50) NOT NULL,
    tipo_delito varchar(30) NOT NULL,
    descripcion_delito text NOT NULL,
    fecha_hecho date NULL,
    hora_hecho time NULL,
    ambito_ocurrencia varchar(20) NOT NULL,
    lugar_hecho text NOT NULL,
    lugar_hecho_municipio_id bigint NULL,
    numero_carpeta_investigacion varchar(100) NOT NULL,
    fiscalia_o_ministerio varchar(200) NOT NULL,
    numero_expediente_judicial varchar(100) NOT NULL,
    juzgado varchar(200) NOT NULL,
    estatus_juridico varchar(30) NOT NULL,
    hay_detenidos boolean NOT NULL,
    datos_detenidos text NOT NULL,
    nna_fue_testigo boolean NOT NULL,
    nna_tambien_victima boolean NOT NULL,
    descripcion_impacto_nna text NOT NULL,
    derivado_por varchar(200) NOT NULL,
    tipo_institucion_derivadora varchar(30) NOT NULL,
    registrado_por_id bigint NULL,
    fecha_registro timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    observaciones text NOT NULL
);

CREATE TABLE web_documentoexpediente (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id bigint NOT NULL,
    tipo varchar(30) NOT NULL,
    nombre_archivo varchar(255) NOT NULL,
    archivo varchar(100) NOT NULL,
    descripcion text NOT NULL,
    fecha_documento date NULL,
    subido_por_id bigint NULL,
    fecha_subida timestamp with time zone NOT NULL
);

-- ------------------------------------------------------------------------
-- RESTITUCIÓN DE DERECHOS (LGDNNA / Caja de Herramientas)
-- ------------------------------------------------------------------------

CREATE TABLE web_derecho (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    clave varchar(6) NOT NULL UNIQUE,
    nombre varchar(200) NOT NULL UNIQUE,
    fundamento varchar(200) NOT NULL,
    descripcion text NOT NULL
);

CREATE TABLE web_institucionejecutora (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar(200) NOT NULL,
    tipo varchar(20) NOT NULL,
    nivel varchar(20) NOT NULL,
    contacto varchar(200) NOT NULL,
    telefono varchar(20) NOT NULL,
    domicilio_id bigint NULL
);

CREATE TABLE web_planrestitucion (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id bigint NOT NULL,
    folio varchar(30) NOT NULL UNIQUE,
    fecha_apertura date NOT NULL,
    elaborado_por_id bigint NULL,
    equipo_id bigint NULL,
    grado_peligro varchar(12) NOT NULL,
    grado_coercion varchar(12) NOT NULL,
    diagnostico_general text NOT NULL,
    determinacion_interes_superior text NOT NULL,
    estatus varchar(15) NOT NULL,
    vigente boolean NOT NULL,
    fecha_cierre date NULL,
    fecha_registro timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL
);

CREATE TABLE web_derechovulnerado (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plan_id bigint NOT NULL,
    derecho_id bigint NOT NULL,
    grado varchar(12) NOT NULL,
    descripcion text NOT NULL
);

CREATE TABLE web_medidaproteccion (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    derecho_vulnerado_id bigint NOT NULL,
    institucion_id bigint NOT NULL,
    tipo varchar(12) NOT NULL,
    descripcion text NOT NULL,
    judicializada boolean NOT NULL,
    responsable_id bigint NULL,
    fecha_solicitud date NULL,
    fecha_inicio date NULL,
    fecha_conclusion date NULL,
    estatus varchar(12) NOT NULL
);

CREATE TABLE web_seguimientomedida (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    medida_id bigint NOT NULL,
    fecha date NOT NULL,
    avance text NOT NULL,
    porcentaje_avance smallint NOT NULL CHECK (porcentaje_avance >= 0),
    registrado_por_id bigint NULL,
    evidencia varchar(100) NOT NULL,
    fecha_registro timestamp with time zone NOT NULL
);

-- ------------------------------------------------------------------------
-- PRIVACIDAD Y PROTECCIÓN DE DATOS
-- ------------------------------------------------------------------------

CREATE TABLE web_consentimientodatos (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id bigint NOT NULL UNIQUE,
    otorgado_por_id bigint NULL,
    version_aviso varchar(20) NOT NULL,
    finalidad text NOT NULL,
    acepta_tratamiento boolean NOT NULL,
    acepta_datos_sensibles boolean NOT NULL,
    permite_uso_estadistico_disociado boolean NOT NULL,
    fecha_otorgamiento date NULL,
    fecha_revocacion date NULL,
    documento varchar(100) NOT NULL,
    fecha_registro timestamp with time zone NOT NULL
);

CREATE TABLE web_solicitudarco (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nna_id bigint NOT NULL,
    tipo varchar(15) NOT NULL,
    solicitante varchar(150) NOT NULL,
    descripcion text NOT NULL,
    fecha_solicitud date NOT NULL,
    estatus varchar(15) NOT NULL,
    fecha_respuesta date NULL,
    resolucion text NOT NULL,
    atendida_por_id bigint NULL
);

CREATE TABLE web_bitacoraacceso (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    usuario_id integer NULL,
    accion varchar(15) NOT NULL,
    modelo varchar(80) NOT NULL,
    objeto_id varchar(40) NOT NULL,
    nna_id bigint NULL,
    ip inet NULL,
    detalle varchar(255) NOT NULL,
    fecha_hora timestamp with time zone NOT NULL
);

-- ===========================================================================
-- LLAVES FORÁNEAS (relaciones del diagrama E-R)
-- ===========================================================================
ALTER TABLE web_municipio ADD CONSTRAINT web_municipio_entidad_id_017587e0_fk_web_entidadfederativa_id FOREIGN KEY (entidad_id) REFERENCES web_entidadfederativa (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_asentamiento ADD CONSTRAINT web_asentamiento_municipio_id_b1309556_fk_web_municipio_id FOREIGN KEY (municipio_id) REFERENCES web_municipio (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_asentamiento ADD CONSTRAINT web_asentamiento_tipo_asentamiento_id_38f15a3a_fk_web_tipoa FOREIGN KEY (tipo_asentamiento_id) REFERENCES web_tipoasentamiento (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_domicilio ADD CONSTRAINT web_domicilio_asentamiento_id_eb2b61a8_fk_web_asentamiento_id FOREIGN KEY (asentamiento_id) REFERENCES web_asentamiento (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_lengua ADD CONSTRAINT web_lengua_familia_id_2f231db2_fk_web_familialinguistica_id FOREIGN KEY (familia_id) REFERENCES web_familialinguistica (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_variantelinguistica ADD CONSTRAINT web_variantelinguistica_lengua_id_3c8bde08_fk_web_lengua_id FOREIGN KEY (lengua_id) REFERENCES web_lengua (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_discapacidad ADD CONSTRAINT web_discapacidad_tipo_id_0e5f60d2_fk_web_tipodiscapacidad_id FOREIGN KEY (tipo_id) REFERENCES web_tipodiscapacidad (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_enfermedad ADD CONSTRAINT web_enfermedad_capitulo_id_718521cb_fk_web_capit FOREIGN KEY (capitulo_id) REFERENCES web_capituloenfermedad (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_empleado ADD CONSTRAINT web_empleado_usuario_id_0df7f9ff_fk_auth_user_id FOREIGN KEY (usuario_id) REFERENCES auth_user (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_empleado ADD CONSTRAINT web_empleado_sexo_catalogo_id_3a11425c_fk_web_sexo_id FOREIGN KEY (sexo_catalogo_id) REFERENCES web_sexo (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_empleado ADD CONSTRAINT web_empleado_domicilio_id_997da189_fk_web_domicilio_id FOREIGN KEY (domicilio_id) REFERENCES web_domicilio (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_equipomultidisciplinario ADD CONSTRAINT web_equipomultidisci_abogado_id_fbebca53_fk_web_emple FOREIGN KEY (abogado_id) REFERENCES web_empleado (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_equipomultidisciplinario ADD CONSTRAINT web_equipomultidisci_doctor_id_c9aa3eac_fk_web_emple FOREIGN KEY (doctor_id) REFERENCES web_empleado (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_equipomultidisciplinario ADD CONSTRAINT web_equipomultidisci_trabajador_social_id_b0013c3e_fk_web_emple FOREIGN KEY (trabajador_social_id) REFERENCES web_empleado (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_equipomultidisciplinario ADD CONSTRAINT web_equipomultidisci_psicologo_id_f86552b1_fk_web_emple FOREIGN KEY (psicologo_id) REFERENCES web_empleado (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_equipomultidisciplinario ADD CONSTRAINT web_equipomultidisci_coordinador_id_5ca912b8_fk_web_emple FOREIGN KEY (coordinador_id) REFERENCES web_empleado (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_tutor ADD CONSTRAINT web_tutor_sexo_catalogo_id_56d952e2_fk_web_sexo_id FOREIGN KEY (sexo_catalogo_id) REFERENCES web_sexo (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_tutor ADD CONSTRAINT web_tutor_domicilio_id_b3890323_fk_web_domicilio_id FOREIGN KEY (domicilio_id) REFERENCES web_domicilio (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nna ADD CONSTRAINT web_nna_sexo_catalogo_id_047dffec_fk_web_sexo_id FOREIGN KEY (sexo_catalogo_id) REFERENCES web_sexo (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nna ADD CONSTRAINT web_nna_lugar_nacimiento_est_2a0354ca_fk_web_entid FOREIGN KEY (lugar_nacimiento_estado_id) REFERENCES web_entidadfederativa (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nna ADD CONSTRAINT web_nna_lugar_nacimiento_mun_431600fa_fk_web_munic FOREIGN KEY (lugar_nacimiento_municipio_id) REFERENCES web_municipio (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nna ADD CONSTRAINT web_nna_domicilio_id_466c36ff_fk_web_domicilio_id FOREIGN KEY (domicilio_id) REFERENCES web_domicilio (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nna ADD CONSTRAINT web_nna_equipo_id_d1bb1e00_fk_web_equipomultidisciplinario_id FOREIGN KEY (equipo_id) REFERENCES web_equipomultidisciplinario (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nna ADD CONSTRAINT web_nna_registrado_por_id_be009cc1_fk_web_empleado_id FOREIGN KEY (registrado_por_id) REFERENCES web_empleado (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nnatutor ADD CONSTRAINT web_nnatutor_nna_id_350a4be8_fk_web_nna_id FOREIGN KEY (nna_id) REFERENCES web_nna (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nnatutor ADD CONSTRAINT web_nnatutor_tutor_id_33323ac4_fk_web_tutor_id FOREIGN KEY (tutor_id) REFERENCES web_tutor (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nacionalidadnna ADD CONSTRAINT web_nacionalidadnna_nna_id_7b580c58_fk_web_nna_id FOREIGN KEY (nna_id) REFERENCES web_nna (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_nacionalidadnna ADD CONSTRAINT web_nacionalidadnna_nacionalidad_id_bf676fda_fk_web_nacio FOREIGN KEY (nacionalidad_id) REFERENCES web_nacionalidad (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_contactonna ADD CONSTRAINT web_contactonna_nna_id_e5290e3a_fk_web_nna_id FOREIGN KEY (nna_id) REFERENCES web_nna (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_contactonna ADD CONSTRAINT web_contactonna_tipo_id_95ec2225_fk_web_tipocontacto_id FOREIGN KEY (tipo_id) REFERENCES web_tipocontacto (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_seguimientonna ADD CONSTRAINT web_seguimientonna_nna_id_71b1d37c_fk_web_nna_id FOREIGN KEY (nna_id) REFERENCES web_nna (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_seguimientonna ADD CONSTRAINT web_seguimientonna_registrado_por_id_a95575ae_fk_web_emple FOREIGN KEY (registrado_por_id) REFERENCES web_empleado (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_idiomanna ADD CONSTRAINT web_idiomanna_nna_id_ff88df3a_fk_web_nna_id FOREIGN KEY (nna_id) REFERENCES web_nna (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_idiomanna ADD CONSTRAINT web_idiomanna_lengua_id_0539b5a3_fk_web_lengua_id FOREIGN KEY (lengua_id) REFERENCES web_lengua (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_idiomanna ADD CONSTRAINT web_idiomanna_variante_id_ae940e14_fk_web_varia FOREIGN KEY (variante_id) REFERENCES web_variantelinguistica (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_idiomanna ADD CONSTRAINT web_idiomanna_nivel_competencia_id_865bea71_fk_web_nivel FOREIGN KEY (nivel_competencia_id) REFERENCES web_nivelcompetenciaoral (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_idiomanna ADD CONSTRAINT web_idiomanna_modo_adquisicion_id_a33a7883_fk_web_modoa FOREIGN KEY (modo_adquisicion_id) REFERENCES web_modoadquisicionlengua (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_discapacidadnna ADD CONSTRAINT web_discapacidadnna_nna_id_285f2fe8_fk_web_nna_id FOREIGN KEY (nna_id) REFERENCES web_nna (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_discapacidadnna ADD CONSTRAINT web_discapacidadnna_tipo_id_99fdb78e_fk_web_tipodiscapacidad_id FOREIGN KEY (tipo_id) REFERENCES web_tipodiscapacidad (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_discapacidadnna ADD CONSTRAINT web_discapacidadnna_discapacidad_id_c78369d3_fk_web_disca FOREIGN KEY (discapacidad_id) REFERENCES web_discapacidad (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_discapacidadnna ADD CONSTRAINT web_discapacidadnna_grado_dependencia_ca_4c0b90cc_fk_web_grado FOREIGN KEY (grado_dependencia_catalogo_id) REFERENCES web_gradodependencia (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_padecimientonna ADD CONSTRAINT web_padecimientonna_nna_id_9e0af0a8_fk_web_nna_id FOREIGN KEY (nna_id) REFERENCES web_nna (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_padecimientonna ADD CONSTRAINT web_padecimientonna_enfermedad_id_dc5f3d40_fk_web_enfermedad_id FOREIGN KEY (enfermedad_id) REFERENCES web_enfermedad (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_hechovictimal ADD CONSTRAINT web_hechovictimal_nna_id_d12055db_fk_web_nna_id FOREIGN KEY (nna_id) REFERENCES web_nna (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_hechovictimal ADD CONSTRAINT web_hechovictimal_lugar_hecho_municipi_51ba31f7_fk_web_munic FOREIGN KEY (lugar_hecho_municipio_id) REFERENCES web_municipio (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_hechovictimal ADD CONSTRAINT web_hechovictimal_registrado_por_id_35c7382f_fk_web_empleado_id FOREIGN KEY (registrado_por_id) REFERENCES web_empleado (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_documentoexpediente ADD CONSTRAINT web_documentoexpediente_nna_id_691c3b36_fk_web_nna_id FOREIGN KEY (nna_id) REFERENCES web_nna (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_documentoexpediente ADD CONSTRAINT web_documentoexpedie_subido_por_id_0f970382_fk_web_emple FOREIGN KEY (subido_por_id) REFERENCES web_empleado (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_institucionejecutora ADD CONSTRAINT web_institucionejecu_domicilio_id_523cf520_fk_web_domic FOREIGN KEY (domicilio_id) REFERENCES web_domicilio (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_planrestitucion ADD CONSTRAINT web_planrestitucion_nna_id_c88fcb4f_fk_web_nna_id FOREIGN KEY (nna_id) REFERENCES web_nna (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_planrestitucion ADD CONSTRAINT web_planrestitucion_elaborado_por_id_46e3b01b_fk_web_emple FOREIGN KEY (elaborado_por_id) REFERENCES web_empleado (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_planrestitucion ADD CONSTRAINT web_planrestitucion_equipo_id_747dd716_fk_web_equip FOREIGN KEY (equipo_id) REFERENCES web_equipomultidisciplinario (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_derechovulnerado ADD CONSTRAINT web_derechovulnerado_plan_id_7ca349ed_fk_web_planrestitucion_id FOREIGN KEY (plan_id) REFERENCES web_planrestitucion (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_derechovulnerado ADD CONSTRAINT web_derechovulnerado_derecho_id_a7c15365_fk_web_derecho_id FOREIGN KEY (derecho_id) REFERENCES web_derecho (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_medidaproteccion ADD CONSTRAINT web_medidaproteccion_derecho_vulnerado_id_a6049343_fk_web_derec FOREIGN KEY (derecho_vulnerado_id) REFERENCES web_derechovulnerado (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_medidaproteccion ADD CONSTRAINT web_medidaproteccion_institucion_id_201e5e27_fk_web_insti FOREIGN KEY (institucion_id) REFERENCES web_institucionejecutora (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_medidaproteccion ADD CONSTRAINT web_medidaproteccion_responsable_id_0bed2a4f_fk_web_empleado_id FOREIGN KEY (responsable_id) REFERENCES web_empleado (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_seguimientomedida ADD CONSTRAINT web_seguimientomedid_medida_id_77e6fcc2_fk_web_medid FOREIGN KEY (medida_id) REFERENCES web_medidaproteccion (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_seguimientomedida ADD CONSTRAINT web_seguimientomedid_registrado_por_id_fdf8c934_fk_web_emple FOREIGN KEY (registrado_por_id) REFERENCES web_empleado (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_consentimientodatos ADD CONSTRAINT web_consentimientodatos_nna_id_e5657ac8_fk_web_nna_id FOREIGN KEY (nna_id) REFERENCES web_nna (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_consentimientodatos ADD CONSTRAINT web_consentimientoda_otorgado_por_id_28decd6e_fk_web_tutor FOREIGN KEY (otorgado_por_id) REFERENCES web_tutor (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_solicitudarco ADD CONSTRAINT web_solicitudarco_nna_id_f532e47a_fk_web_nna_id FOREIGN KEY (nna_id) REFERENCES web_nna (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_solicitudarco ADD CONSTRAINT web_solicitudarco_atendida_por_id_12722197_fk_web_empleado_id FOREIGN KEY (atendida_por_id) REFERENCES web_empleado (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_bitacoraacceso ADD CONSTRAINT web_bitacoraacceso_usuario_id_37ecff22_fk_auth_user_id FOREIGN KEY (usuario_id) REFERENCES auth_user (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_bitacoraacceso ADD CONSTRAINT web_bitacoraacceso_nna_id_8c0bcc52_fk_web_nna_id FOREIGN KEY (nna_id) REFERENCES web_nna (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_contactotutor ADD CONSTRAINT web_contactotutor_tutor_id_80da3815_fk_web_tutor_id FOREIGN KEY (tutor_id) REFERENCES web_tutor (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_contactotutor ADD CONSTRAINT web_contactotutor_tipo_id_18ea38b0_fk_web_tipocontacto_id FOREIGN KEY (tipo_id) REFERENCES web_tipocontacto (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_contactoempleado ADD CONSTRAINT web_contactoempleado_empleado_id_521a0f1f_fk_web_empleado_id FOREIGN KEY (empleado_id) REFERENCES web_empleado (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE web_contactoempleado ADD CONSTRAINT web_contactoempleado_tipo_id_bd918b5c_fk_web_tipocontacto_id FOREIGN KEY (tipo_id) REFERENCES web_tipocontacto (id) DEFERRABLE INITIALLY DEFERRED;

-- ===========================================================================
-- TRIGGERS: auto-actualización de fecha_actualizacion
-- ===========================================================================
CREATE TRIGGER trg_web_tutor_fecha_actualizacion BEFORE UPDATE ON web_tutor
    FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();
CREATE TRIGGER trg_web_nna_fecha_actualizacion BEFORE UPDATE ON web_nna
    FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();
CREATE TRIGGER trg_web_seguimientonna_fecha_actualizacion BEFORE UPDATE ON web_seguimientonna
    FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();
CREATE TRIGGER trg_web_hechovictimal_fecha_actualizacion BEFORE UPDATE ON web_hechovictimal
    FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();
CREATE TRIGGER trg_web_planrestitucion_fecha_actualizacion BEFORE UPDATE ON web_planrestitucion
    FOR EACH ROW EXECUTE FUNCTION set_fecha_actualizacion();

-- ===========================================================================
-- ÍNDICES
-- ===========================================================================
CREATE INDEX web_entidadfederativa_clave_ea36db2c_like ON web_entidadfederativa (clave varchar_pattern_ops);
CREATE INDEX web_municipio_entidad_id_017587e0 ON web_municipio (entidad_id);
CREATE INDEX web_tipoasentamiento_nombre_1a4aa621_like ON web_tipoasentamiento (nombre varchar_pattern_ops);
CREATE INDEX web_asentamiento_municipio_id_b1309556 ON web_asentamiento (municipio_id);
CREATE INDEX web_asentamiento_tipo_asentamiento_id_38f15a3a ON web_asentamiento (tipo_asentamiento_id);
CREATE INDEX web_asentamiento_codigo_postal_adb4679a ON web_asentamiento (codigo_postal);
CREATE INDEX web_asentamiento_codigo_postal_adb4679a_like ON web_asentamiento (codigo_postal varchar_pattern_ops);
CREATE INDEX web_domicilio_asentamiento_id_eb2b61a8 ON web_domicilio (asentamiento_id);
CREATE INDEX web_sexo_clave_f59b1fe2_like ON web_sexo (clave varchar_pattern_ops);
CREATE INDEX web_sexo_nombre_294eb8fd_like ON web_sexo (nombre varchar_pattern_ops);
CREATE INDEX web_nacionalidad_clave_12e3da0e_like ON web_nacionalidad (clave varchar_pattern_ops);
CREATE INDEX web_nacionalidad_nombre_2dc7ce72_like ON web_nacionalidad (nombre varchar_pattern_ops);
CREATE INDEX web_tipocontacto_clave_f55f6567_like ON web_tipocontacto (clave varchar_pattern_ops);
CREATE INDEX web_tipocontacto_nombre_2bb9bfae_like ON web_tipocontacto (nombre varchar_pattern_ops);
CREATE INDEX web_nivelcompetenciaoral_clave_9b14497e_like ON web_nivelcompetenciaoral (clave varchar_pattern_ops);
CREATE INDEX web_nivelcompetenciaoral_nombre_6d15bfc8_like ON web_nivelcompetenciaoral (nombre varchar_pattern_ops);
CREATE INDEX web_modoadquisicionlengua_clave_1298818d_like ON web_modoadquisicionlengua (clave varchar_pattern_ops);
CREATE INDEX web_gradodependencia_clave_4f4bbf0d_like ON web_gradodependencia (clave varchar_pattern_ops);
CREATE INDEX web_gradodependencia_nombre_d8948dd7_like ON web_gradodependencia (nombre varchar_pattern_ops);
CREATE INDEX web_familialinguistica_nombre_ae270436_like ON web_familialinguistica (nombre varchar_pattern_ops);
CREATE INDEX web_lengua_familia_id_2f231db2 ON web_lengua (familia_id);
CREATE INDEX web_lengua_clave_inali_870d1b6f_like ON web_lengua (clave_inali varchar_pattern_ops);
CREATE INDEX web_variantelinguistica_lengua_id_3c8bde08 ON web_variantelinguistica (lengua_id);
CREATE INDEX web_tipodiscapacidad_nombre_e9b18023_like ON web_tipodiscapacidad (nombre varchar_pattern_ops);
CREATE INDEX web_discapacidad_tipo_id_0e5f60d2 ON web_discapacidad (tipo_id);
CREATE INDEX web_capituloenfermedad_codigo_9e954438_like ON web_capituloenfermedad (codigo varchar_pattern_ops);
CREATE INDEX web_enfermedad_capitulo_id_718521cb ON web_enfermedad (capitulo_id);
CREATE INDEX web_enfermedad_codigo_cie10_c08658da_like ON web_enfermedad (codigo_cie10 varchar_pattern_ops);
CREATE INDEX web_empleado_rfc_fc94f31a_like ON web_empleado (rfc varchar_pattern_ops);
CREATE INDEX web_empleado_curp_820336d7_like ON web_empleado (curp varchar_pattern_ops);
CREATE INDEX web_empleado_sexo_catalogo_id_3a11425c ON web_empleado (sexo_catalogo_id);
CREATE INDEX web_empleado_domicilio_id_997da189 ON web_empleado (domicilio_id);
CREATE INDEX web_equipomultidisciplinario_abogado_id_fbebca53 ON web_equipomultidisciplinario (abogado_id);
CREATE INDEX web_equipomultidisciplinario_doctor_id_c9aa3eac ON web_equipomultidisciplinario (doctor_id);
CREATE INDEX web_equipomultidisciplinario_trabajador_social_id_b0013c3e ON web_equipomultidisciplinario (trabajador_social_id);
CREATE INDEX web_equipomultidisciplinario_psicologo_id_f86552b1 ON web_equipomultidisciplinario (psicologo_id);
CREATE INDEX web_equipomultidisciplinario_coordinador_id_5ca912b8 ON web_equipomultidisciplinario (coordinador_id);
CREATE INDEX web_tutor_sexo_catalogo_id_56d952e2 ON web_tutor (sexo_catalogo_id);
CREATE INDEX web_tutor_curp_e8ce7141_like ON web_tutor (curp varchar_pattern_ops);
CREATE INDEX web_tutor_domicilio_id_b3890323 ON web_tutor (domicilio_id);
CREATE INDEX web_nna_folio_nna_8a684fd5_like ON web_nna (folio_nna varchar_pattern_ops);
CREATE INDEX web_nna_sexo_catalogo_id_047dffec ON web_nna (sexo_catalogo_id);
CREATE INDEX web_nna_curp_594524bb_like ON web_nna (curp varchar_pattern_ops);
CREATE INDEX web_nna_lugar_nacimiento_estado_id_2a0354ca ON web_nna (lugar_nacimiento_estado_id);
CREATE INDEX web_nna_lugar_nacimiento_municipio_id_431600fa ON web_nna (lugar_nacimiento_municipio_id);
CREATE INDEX web_nna_domicilio_id_466c36ff ON web_nna (domicilio_id);
CREATE INDEX web_nna_equipo_id_d1bb1e00 ON web_nna (equipo_id);
CREATE INDEX web_nna_registrado_por_id_be009cc1 ON web_nna (registrado_por_id);
CREATE UNIQUE INDEX un_tutor_principal_por_nna ON web_nnatutor (nna_id) WHERE principal;
CREATE INDEX web_nnatutor_nna_id_350a4be8 ON web_nnatutor (nna_id);
CREATE INDEX web_nnatutor_tutor_id_33323ac4 ON web_nnatutor (tutor_id);
CREATE INDEX web_nacionalidadnna_nna_id_7b580c58 ON web_nacionalidadnna (nna_id);
CREATE INDEX web_nacionalidadnna_nacionalidad_id_bf676fda ON web_nacionalidadnna (nacionalidad_id);
CREATE INDEX web_contactonna_nna_id_e5290e3a ON web_contactonna (nna_id);
CREATE INDEX web_contactonna_tipo_id_95ec2225 ON web_contactonna (tipo_id);
CREATE INDEX web_seguimientonna_nna_id_71b1d37c ON web_seguimientonna (nna_id);
CREATE INDEX web_seguimientonna_registrado_por_id_a95575ae ON web_seguimientonna (registrado_por_id);
CREATE INDEX web_idiomanna_nna_id_ff88df3a ON web_idiomanna (nna_id);
CREATE INDEX web_idiomanna_lengua_id_0539b5a3 ON web_idiomanna (lengua_id);
CREATE INDEX web_idiomanna_variante_id_ae940e14 ON web_idiomanna (variante_id);
CREATE INDEX web_idiomanna_nivel_competencia_id_865bea71 ON web_idiomanna (nivel_competencia_id);
CREATE INDEX web_idiomanna_modo_adquisicion_id_a33a7883 ON web_idiomanna (modo_adquisicion_id);
CREATE INDEX web_discapacidadnna_nna_id_285f2fe8 ON web_discapacidadnna (nna_id);
CREATE INDEX web_discapacidadnna_tipo_id_99fdb78e ON web_discapacidadnna (tipo_id);
CREATE INDEX web_discapacidadnna_discapacidad_id_c78369d3 ON web_discapacidadnna (discapacidad_id);
CREATE INDEX web_discapacidadnna_grado_dependencia_catalogo_id_4c0b90cc ON web_discapacidadnna (grado_dependencia_catalogo_id);
CREATE INDEX web_padecimientonna_nna_id_9e0af0a8 ON web_padecimientonna (nna_id);
CREATE INDEX web_padecimientonna_enfermedad_id_dc5f3d40 ON web_padecimientonna (enfermedad_id);
CREATE INDEX web_hechovictimal_lugar_hecho_municipio_id_51ba31f7 ON web_hechovictimal (lugar_hecho_municipio_id);
CREATE INDEX web_hechovictimal_registrado_por_id_35c7382f ON web_hechovictimal (registrado_por_id);
CREATE INDEX web_documentoexpediente_nna_id_691c3b36 ON web_documentoexpediente (nna_id);
CREATE INDEX web_documentoexpediente_subido_por_id_0f970382 ON web_documentoexpediente (subido_por_id);
CREATE INDEX web_derecho_clave_fbccd61d_like ON web_derecho (clave varchar_pattern_ops);
CREATE INDEX web_derecho_nombre_ad82033c_like ON web_derecho (nombre varchar_pattern_ops);
CREATE INDEX web_institucionejecutora_domicilio_id_523cf520 ON web_institucionejecutora (domicilio_id);
CREATE UNIQUE INDEX un_plan_vigente_por_nna ON web_planrestitucion (nna_id) WHERE vigente;
CREATE INDEX web_planrestitucion_nna_id_c88fcb4f ON web_planrestitucion (nna_id);
CREATE INDEX web_planrestitucion_folio_9840b3bf_like ON web_planrestitucion (folio varchar_pattern_ops);
CREATE INDEX web_planrestitucion_elaborado_por_id_46e3b01b ON web_planrestitucion (elaborado_por_id);
CREATE INDEX web_planrestitucion_equipo_id_747dd716 ON web_planrestitucion (equipo_id);
CREATE INDEX web_derechovulnerado_plan_id_7ca349ed ON web_derechovulnerado (plan_id);
CREATE INDEX web_derechovulnerado_derecho_id_a7c15365 ON web_derechovulnerado (derecho_id);
CREATE INDEX web_medidaproteccion_derecho_vulnerado_id_a6049343 ON web_medidaproteccion (derecho_vulnerado_id);
CREATE INDEX web_medidaproteccion_institucion_id_201e5e27 ON web_medidaproteccion (institucion_id);
CREATE INDEX web_medidaproteccion_responsable_id_0bed2a4f ON web_medidaproteccion (responsable_id);
CREATE INDEX web_seguimientomedida_medida_id_77e6fcc2 ON web_seguimientomedida (medida_id);
CREATE INDEX web_seguimientomedida_registrado_por_id_fdf8c934 ON web_seguimientomedida (registrado_por_id);
CREATE INDEX web_consentimientodatos_otorgado_por_id_28decd6e ON web_consentimientodatos (otorgado_por_id);
CREATE INDEX web_solicitudarco_nna_id_f532e47a ON web_solicitudarco (nna_id);
CREATE INDEX web_solicitudarco_atendida_por_id_12722197 ON web_solicitudarco (atendida_por_id);
CREATE INDEX web_bitacoraacceso_usuario_id_37ecff22 ON web_bitacoraacceso (usuario_id);
CREATE INDEX web_bitacoraacceso_nna_id_8c0bcc52 ON web_bitacoraacceso (nna_id);
CREATE INDEX web_bitacoraacceso_fecha_hora_b410f5ea ON web_bitacoraacceso (fecha_hora);
CREATE INDEX web_contactotutor_tutor_id_80da3815 ON web_contactotutor (tutor_id);
CREATE INDEX web_contactotutor_tipo_id_18ea38b0 ON web_contactotutor (tipo_id);
CREATE INDEX web_contactoempleado_empleado_id_521a0f1f ON web_contactoempleado (empleado_id);
CREATE INDEX web_contactoempleado_tipo_id_bd918b5c ON web_contactoempleado (tipo_id);
ALTER TABLE web_municipio ADD CONSTRAINT web_municipio_entidad_id_clave_65aa5b27_uniq UNIQUE (entidad_id, clave);
ALTER TABLE web_discapacidad ADD CONSTRAINT web_discapacidad_tipo_id_nombre_11830183_uniq UNIQUE (tipo_id, nombre);
ALTER TABLE web_nnatutor ADD CONSTRAINT web_nnatutor_nna_id_tutor_id_ffd7a462_uniq UNIQUE (nna_id, tutor_id);
ALTER TABLE web_nacionalidadnna ADD CONSTRAINT web_nacionalidadnna_nna_id_nacionalidad_id_1c58c77a_uniq UNIQUE (nna_id, nacionalidad_id);
ALTER TABLE web_contactonna ADD CONSTRAINT web_contactonna_nna_id_tipo_id_valor_78a9bb49_uniq UNIQUE (nna_id, tipo_id, valor);
ALTER TABLE web_idiomanna ADD CONSTRAINT web_idiomanna_nna_id_lengua_id_variante_id_83e2f774_uniq UNIQUE (nna_id, lengua_id, variante_id);
ALTER TABLE web_discapacidadnna ADD CONSTRAINT web_discapacidadnna_nna_id_tipo_id_descripci_3a1940fa_uniq UNIQUE (nna_id, tipo_id, descripcion_especifica);
ALTER TABLE web_padecimientonna ADD CONSTRAINT web_padecimientonna_nna_id_enfermedad_id_76da1ff2_uniq UNIQUE (nna_id, enfermedad_id);
ALTER TABLE web_institucionejecutora ADD CONSTRAINT web_institucionejecutora_nombre_nivel_1956484a_uniq UNIQUE (nombre, nivel);
ALTER TABLE web_derechovulnerado ADD CONSTRAINT web_derechovulnerado_plan_id_derecho_id_2dfb6e85_uniq UNIQUE (plan_id, derecho_id);
ALTER TABLE web_contactotutor ADD CONSTRAINT web_contactotutor_tutor_id_tipo_id_valor_88b24a3d_uniq UNIQUE (tutor_id, tipo_id, valor);
ALTER TABLE web_contactoempleado ADD CONSTRAINT web_contactoempleado_empleado_id_tipo_id_valor_a541a4e1_uniq UNIQUE (empleado_id, tipo_id, valor);

COMMIT;
