# Generated by Django 5.2.11 on 2026-02-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('edad', models.IntegerField()),
                ('direccion', models.TextField()),
                ('rol', models.CharField(choices=[('director', 'Director'), ('coordinador', 'Coordinador'), ('psicologo', 'Psicólogo'), ('doctor', 'Doctor'), ('abogado', 'Abogado'), ('trabajador_social', 'Trabajador Social'), ('analista', 'Analista'), ('voluntario', 'Voluntario')], max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
