# Generated by Django 5.2.11 on 2026-02-23 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField()),
                ('rol', models.CharField(choices=[('director', 'Director'), ('coordinador', 'Coordinador'), ('psicologo', 'Psicólogo'), ('doctor', 'Doctor'), ('abogado', 'Abogado'), ('trabajador_social', 'Trabajador Social'), ('analista', 'Analista'), ('voluntario', 'Voluntario')], max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
