# Generated by Django 5.2.11 on 2026-02-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_trabajador',
            field=models.CharField(choices=[('empleado', 'Empleado'), ('voluntario', 'Voluntario')], default='empleado', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('director', 'Director'), ('coordinador', 'Coordinador'), ('psicologo', 'Psicólogo'), ('doctor', 'Doctor'), ('abogado', 'Abogado'), ('trabajador_social', 'Trabajador Social'), ('analista', 'Analista')], max_length=50),
        ),
    ]
