# Generated by Django 5.2.11 on 2026-06-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lengua',
            name='clave_inali',
            field=models.CharField(blank=True, help_text='Clave oficial INALI (ej. NAH para Náhuatl)', max_length=20, null=True, unique=True),
        ),
    ]
