# Generated by Django 5.2.11 on 2026-06-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_lengua_clave_inali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodiscapacidad',
            name='clave_inegi',
            field=models.CharField(blank=True, help_text='Clave INEGI si aplica', max_length=10, null=True),
        ),
    ]
