# Generated by Django 5.2.11 on 2026-02-26 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_empleado_activo_empleado_tipo_trabajador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='activo',
        ),
    ]
