# Generated by Codex on 2026-06-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_asentamiento_capituloenfermedad_entidadfederativa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoNNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('social', 'Social'), ('medica', 'Médica'), ('psicologica', 'Psicológica'), ('legal', 'Legal'), ('general', 'General')], max_length=20)),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('acuerdos', models.TextField(blank=True)),
                ('proxima_accion', models.TextField(blank=True)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('concluido', 'Concluido')], default='pendiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='web.nna')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_registrados', to='web.empleado')),
            ],
            options={
                'verbose_name': 'Seguimiento del NNA',
                'verbose_name_plural': 'Seguimientos del NNA',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
