# Generated by Django 5.2.11 on 2026-06-11 06:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_seguimientonna'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Derecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text="Fraccion del Art. 13, p.ej. 'IX'", max_length=6, unique=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('fundamento', models.CharField(blank=True, help_text='Articulo(s) LGDNNA que lo desarrollan', max_length=200)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Derecho (Art. 13 LGDNNA)',
                'verbose_name_plural': 'Catalogo de Derechos (LGDNNA)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('consulta', 'Consulta'), ('creacion', 'Creacion'), ('modificacion', 'Modificacion'), ('eliminacion', 'Eliminacion'), ('exportacion', 'Exportacion')], max_length=15)),
                ('modelo', models.CharField(max_length=80)),
                ('objeto_id', models.CharField(blank=True, max_length=40)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('nna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_bitacora', to='web.nna')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitacora de Acceso',
                'verbose_name_plural': 'Bitacora de Accesos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ConsentimientoDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_aviso', models.CharField(default='1.0', max_length=20)),
                ('finalidad', models.TextField(help_text='Finalidad del tratamiento informada al titular')),
                ('acepta_tratamiento', models.BooleanField(default=False)),
                ('acepta_datos_sensibles', models.BooleanField(default=False)),
                ('permite_uso_estadistico_disociado', models.BooleanField(default=True, help_text='Permite uso estadistico previa disociacion (anonimizacion)')),
                ('fecha_otorgamiento', models.DateField(blank=True, null=True)),
                ('fecha_revocacion', models.DateField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, upload_to='consentimientos/%Y/%m/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consentimiento', to='web.nna')),
                ('otorgado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='web.tutor')),
            ],
            options={
                'verbose_name': 'Consentimiento de Datos',
                'verbose_name_plural': 'Consentimientos de Datos',
            },
        ),
        migrations.CreateModel(
            name='DerechoVulnerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(choices=[('riesgo', 'En riesgo'), ('restringido', 'Restringido'), ('vulnerado', 'Vulnerado')], default='vulnerado', max_length=12)),
                ('descripcion', models.TextField(blank=True)),
                ('derecho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vulneraciones', to='web.derecho')),
            ],
            options={
                'verbose_name': 'Derecho Vulnerado',
                'verbose_name_plural': 'Derechos Vulnerados',
            },
        ),
        migrations.CreateModel(
            name='InstitucionEjecutora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('salud', 'Salud'), ('educacion', 'Educacion'), ('dif', 'DIF'), ('procuraduria', 'Procuraduria de Proteccion'), ('fiscalia', 'Fiscalia / Ministerio Publico'), ('seguridad', 'Seguridad publica'), ('cdh', 'Comision de Derechos Humanos'), ('asistencia', 'Asistencia social'), ('otra', 'Otra')], max_length=20)),
                ('nivel', models.CharField(choices=[('federal', 'Federal'), ('estatal', 'Estatal'), ('municipal', 'Municipal'), ('sociedad_civil', 'Sociedad civil'), ('internacional', 'Internacional')], max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instituciones', to='web.domicilio')),
            ],
            options={
                'verbose_name': 'Institucion Ejecutora',
                'verbose_name_plural': 'Instituciones Ejecutoras',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'nivel')},
            },
        ),
        migrations.CreateModel(
            name='MedidaProteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('urgente', 'Urgente / cautelar'), ('especial', 'Proteccion especial'), ('ordinaria', 'Ordinaria')], default='especial', max_length=12)),
                ('descripcion', models.TextField()),
                ('judicializada', models.BooleanField(default=False, help_text='Se promovio judicializacion? (Caja 4.5.2.b)')),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_conclusion', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('solicitada', 'Solicitada'), ('en_proceso', 'En proceso'), ('cumplida', 'Cumplida'), ('no_cumplida', 'No cumplida'), ('cancelada', 'Cancelada')], default='solicitada', max_length=12)),
                ('derecho_vulnerado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='web.derechovulnerado')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medidas', to='web.institucionejecutora')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidas_responsable', to='web.empleado')),
            ],
            options={
                'verbose_name': 'Medida de Proteccion',
                'verbose_name_plural': 'Medidas de Proteccion',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='PlanRestitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30, unique=True)),
                ('fecha_apertura', models.DateField()),
                ('grado_peligro', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('inminente', 'Riesgo inminente')], help_text='Peligro a la integridad fisica/emocional (Caja 4.4.1)', max_length=12)),
                ('grado_coercion', models.CharField(choices=[('nula', 'Nula'), ('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], help_text='Grado de coercion (Caja 4.4.2)', max_length=12)),
                ('diagnostico_general', models.TextField(blank=True)),
                ('determinacion_interes_superior', models.TextField(blank=True, help_text='Evaluacion y determinacion del interes superior (LGDNNA Art. 18)')),
                ('estatus', models.CharField(choices=[('diagnostico', 'En diagnostico'), ('ejecucion', 'En ejecucion'), ('seguimiento', 'En seguimiento'), ('concluido', 'Concluido'), ('suspendido', 'Suspendido')], default='diagnostico', max_length=15)),
                ('vigente', models.BooleanField(default=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('elaborado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_elaborados', to='web.empleado')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes', to='web.equipomultidisciplinario')),
                ('nna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_restitucion', to='web.nna')),
            ],
            options={
                'verbose_name': 'Plan de Restitucion de Derechos',
                'verbose_name_plural': 'Planes de Restitucion de Derechos',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='derechovulnerado',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derechos_vulnerados', to='web.planrestitucion'),
        ),
        migrations.CreateModel(
            name='SeguimientoMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('avance', models.TextField()),
                ('porcentaje_avance', models.PositiveSmallIntegerField(default=0, help_text='Avance acumulado de la medida (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('evidencia', models.FileField(blank=True, upload_to='seguimientos/%Y/%m/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='web.medidaproteccion')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_medida', to='web.empleado')),
            ],
            options={
                'verbose_name': 'Seguimiento de Medida',
                'verbose_name_plural': 'Seguimientos de Medidas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudARCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acceso', 'Acceso'), ('rectificacion', 'Rectificacion'), ('cancelacion', 'Cancelacion'), ('oposicion', 'Oposicion'), ('revocacion', 'Revocacion del consentimiento')], max_length=15)),
                ('solicitante', models.CharField(help_text='Persona que ejerce el derecho ARCO', max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateField()),
                ('estatus', models.CharField(choices=[('recibida', 'Recibida'), ('en_tramite', 'En tramite'), ('procedente', 'Procedente'), ('improcedente', 'Improcedente')], default='recibida', max_length=15)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('resolucion', models.TextField(blank=True)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arco_atendidas', to='web.empleado')),
                ('nna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_arco', to='web.nna')),
            ],
            options={
                'verbose_name': 'Solicitud ARCO',
                'verbose_name_plural': 'Solicitudes ARCO',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.AddConstraint(
            model_name='planrestitucion',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('nna',), name='un_plan_vigente_por_nna'),
        ),
        migrations.AlterUniqueTogether(
            name='derechovulnerado',
            unique_together={('plan', 'derecho')},
        ),
    ]
