# Generated by Django 5.2.11 on 2026-06-13 15:39

import django.db.models.deletion
from django.db import migrations, models


def _dedupe_by_fields(Model, field_names):
    seen = set()
    duplicate_ids = []
    for obj in Model.objects.order_by('id'):
        key = []
        for field_name in field_names:
            if field_name.endswith('_id'):
                key.append(getattr(obj, field_name))
            else:
                field = Model._meta.get_field(field_name)
                key.append(getattr(obj, field.attname if field.is_relation else field_name))
        key = tuple(key)
        if key in seen:
            duplicate_ids.append(obj.id)
        else:
            seen.add(key)
    if duplicate_ids:
        Model.objects.filter(id__in=duplicate_ids).delete()


def dedupe_existing_data(apps, schema_editor):
    _dedupe_by_fields(apps.get_model('web', 'Asentamiento'), ['municipio', 'codigo_postal', 'nombre'])
    _dedupe_by_fields(apps.get_model('web', 'DiscapacidadNNA'), ['nna', 'tipo', 'descripcion_especifica'])
    _dedupe_by_fields(apps.get_model('web', 'DiscapacidadTutor'), ['tutor', 'tipo', 'descripcion_especifica'])
    _dedupe_by_fields(apps.get_model('web', 'PadecimientoNNA'), ['nna', 'enfermedad'])
    _dedupe_by_fields(apps.get_model('web', 'PadecimientoTutor'), ['tutor', 'enfermedad'])


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_seed_derechos_instituciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoNNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('principal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contacto del NNA',
                'verbose_name_plural': 'Contactos del NNA',
                'ordering': ['-principal', 'tipo__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Discapacidad',
                'verbose_name_plural': 'Discapacidades',
                'ordering': ['tipo__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GradoDependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Grado de Dependencia',
                'verbose_name_plural': 'Grados de Dependencia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ModoAdquisicionLengua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30, unique=True)),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('contexto', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Modo de Adquisicion de Lengua',
                'verbose_name_plural': 'Modos de Adquisicion de Lengua',
                'ordering': ['categoria'],
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='NacionalidadNNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nacionalidad del NNA',
                'verbose_name_plural': 'Nacionalidades del NNA',
            },
        ),
        migrations.CreateModel(
            name='NivelCompetenciaOral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('significado', models.TextField(blank=True)),
                ('puede_declarar', models.BooleanField(default=True)),
                ('requiere_interprete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Nivel de Competencia Oral',
                'verbose_name_plural': 'Niveles de Competencia Oral',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NNATutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(blank=True, max_length=30)),
                ('principal', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tutor del NNA',
                'verbose_name_plural': 'Tutores del NNA',
                'ordering': ['-principal', 'tutor__apellido_paterno', 'tutor__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Catalogo de Sexo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Contacto',
                'verbose_name_plural': 'Tipos de Contacto',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='idiomanna',
            name='autodenominacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='idiomanna',
            name='preferente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idiomatutor',
            name='autodenominacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='nna',
            name='folio_nna',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='web.domicilio'),
        ),
        migrations.AlterField(
            model_name='nna',
            name='domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nna', to='web.domicilio'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutores', to='web.domicilio'),
        ),
        migrations.RunPython(dedupe_existing_data, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='discapacidadnna',
            unique_together={('nna', 'tipo', 'descripcion_especifica')},
        ),
        migrations.AlterUniqueTogether(
            name='discapacidadtutor',
            unique_together={('tutor', 'tipo', 'descripcion_especifica')},
        ),
        migrations.AlterUniqueTogether(
            name='padecimientonna',
            unique_together={('nna', 'enfermedad')},
        ),
        migrations.AlterUniqueTogether(
            name='padecimientotutor',
            unique_together={('tutor', 'enfermedad')},
        ),
        migrations.AddConstraint(
            model_name='asentamiento',
            constraint=models.UniqueConstraint(fields=('municipio', 'codigo_postal', 'nombre'), name='uniq_asentamiento_municipio_cp_nombre'),
        ),
        migrations.AddField(
            model_name='contactonna',
            name='nna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='web.nna'),
        ),
        migrations.AddField(
            model_name='discapacidad',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discapacidades', to='web.tipodiscapacidad'),
        ),
        migrations.AddField(
            model_name='discapacidadnna',
            name='discapacidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.discapacidad'),
        ),
        migrations.AddField(
            model_name='discapacidadtutor',
            name='discapacidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.discapacidad'),
        ),
        migrations.AddField(
            model_name='discapacidadnna',
            name='grado_dependencia_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discapacidades_nna', to='web.gradodependencia'),
        ),
        migrations.AddField(
            model_name='discapacidadtutor',
            name='grado_dependencia_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discapacidades_tutor', to='web.gradodependencia'),
        ),
        migrations.AddField(
            model_name='idiomanna',
            name='modo_adquisicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idiomas_nna', to='web.modoadquisicionlengua'),
        ),
        migrations.AddField(
            model_name='idiomatutor',
            name='modo_adquisicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idiomas_tutor', to='web.modoadquisicionlengua'),
        ),
        migrations.AddField(
            model_name='nacionalidadnna',
            name='nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nna_relacion', to='web.nacionalidad'),
        ),
        migrations.AddField(
            model_name='nacionalidadnna',
            name='nna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nacionalidades_relacion', to='web.nna'),
        ),
        migrations.AddField(
            model_name='nna',
            name='nacionalidades',
            field=models.ManyToManyField(blank=True, related_name='nna', through='web.NacionalidadNNA', to='web.nacionalidad'),
        ),
        migrations.AddField(
            model_name='idiomanna',
            name='nivel_competencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idiomas_nna', to='web.nivelcompetenciaoral'),
        ),
        migrations.AddField(
            model_name='idiomatutor',
            name='nivel_competencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idiomas_tutor', to='web.nivelcompetenciaoral'),
        ),
        migrations.AddField(
            model_name='nnatutor',
            name='nna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores_relacion', to='web.nna'),
        ),
        migrations.AddField(
            model_name='nnatutor',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nna_relacionados', to='web.tutor'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sexo_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='web.sexo'),
        ),
        migrations.AddField(
            model_name='nna',
            name='sexo_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nna', to='web.sexo'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='sexo_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tutores', to='web.sexo'),
        ),
        migrations.AddField(
            model_name='contactonna',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos_nna', to='web.tipocontacto'),
        ),
        migrations.AlterUniqueTogether(
            name='discapacidad',
            unique_together={('tipo', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='nacionalidadnna',
            unique_together={('nna', 'nacionalidad')},
        ),
        migrations.AddConstraint(
            model_name='nnatutor',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('nna',), name='un_tutor_principal_por_nna'),
        ),
        migrations.AlterUniqueTogether(
            name='nnatutor',
            unique_together={('nna', 'tutor')},
        ),
        migrations.AlterUniqueTogether(
            name='contactonna',
            unique_together={('nna', 'tipo', 'valor')},
        ),
    ]
