# Generated by Django 5.2.11 on 2026-06-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_seed_catalogos_base_y_backfill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lengua',
            options={'ordering': ['catalogo_id', 'nombre'], 'verbose_name': 'Lengua', 'verbose_name_plural': 'Lenguas'},
        ),
        migrations.AddField(
            model_name='familialinguistica',
            name='catalogo_id',
            field=models.PositiveIntegerField(blank=True, help_text='Id del catalogo proporcionado por la escuela/profesor', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lengua',
            name='agrupacion_linguistica',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lengua',
            name='autodenominacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lengua',
            name='catalogo_id',
            field=models.PositiveIntegerField(blank=True, help_text='Id del catalogo proporcionado por la escuela/profesor', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lengua',
            name='estado_region',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lengua',
            name='variante_linguistica',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
