# Generated by Django 5.2.11 on 2026-06-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_recarga_catalogos_y_cie10'),
    ]

    operations = [
        migrations.AddField(
            model_name='nna',
            name='comunidad_indigena',
            field=models.CharField(blank=True, help_text='Pueblo o comunidad indigena', max_length=150),
        ),
        migrations.AddField(
            model_name='nna',
            name='condicion_migratoria',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('migrante', 'Migrante'), ('refugiado', 'Refugiado/a'), ('asilado', 'Asilado/a politico/a'), ('repatriado', 'Repatriado/a')], default='ninguna', max_length=12),
        ),
        migrations.AddField(
            model_name='nna',
            name='lengua_interprete',
            field=models.CharField(blank=True, help_text='Lengua para la que requiere interprete', max_length=100),
        ),
        migrations.AddField(
            model_name='nna',
            name='pais_destino',
            field=models.CharField(blank=True, help_text='Pais de destino (si es migrante)', max_length=100),
        ),
        migrations.AddField(
            model_name='nna',
            name='pertenece_comunidad_indigena',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nna',
            name='requiere_interprete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nna',
            name='situacion_calle',
            field=models.BooleanField(default=False, help_text='Se encuentra en situacion de calle'),
        ),
        migrations.CreateModel(
            name='ContactoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('principal', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='web.empleado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos_empleado', to='web.tipocontacto')),
            ],
            options={
                'verbose_name': 'Contacto del Empleado',
                'verbose_name_plural': 'Contactos del Empleado',
                'ordering': ['-principal', 'tipo__nombre'],
                'unique_together': {('empleado', 'tipo', 'valor')},
            },
        ),
        migrations.CreateModel(
            name='ContactoTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('principal', models.BooleanField(default=False)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos_tutor', to='web.tipocontacto')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='web.tutor')),
            ],
            options={
                'verbose_name': 'Contacto del Tutor',
                'verbose_name_plural': 'Contactos del Tutor',
                'ordering': ['-principal', 'tipo__nombre'],
                'unique_together': {('tutor', 'tipo', 'valor')},
            },
        ),
    ]
