# Generated by Django 5.2.11 on 2026-06-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_nna_comunidad_indigena_nna_condicion_migratoria_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='idiomatutor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='idiomatutor',
            name='lengua',
        ),
        migrations.RemoveField(
            model_name='idiomatutor',
            name='modo_adquisicion',
        ),
        migrations.RemoveField(
            model_name='idiomatutor',
            name='nivel_competencia',
        ),
        migrations.RemoveField(
            model_name='idiomatutor',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='idiomatutor',
            name='variante',
        ),
        migrations.AlterUniqueTogether(
            name='padecimientotutor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='padecimientotutor',
            name='enfermedad',
        ),
        migrations.RemoveField(
            model_name='padecimientotutor',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='DiscapacidadTutor',
        ),
        migrations.DeleteModel(
            name='IdiomaTutor',
        ),
        migrations.DeleteModel(
            name='PadecimientoTutor',
        ),
    ]
