# Generated by Django 5.2.11 on 2026-06-20 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_idiomatutor_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nna',
            name='estatus_proceso',
            field=models.CharField(choices=[('ingreso', 'Ingreso / registro'), ('valoracion', 'Valoración inicial'), ('diagnostico', 'Diagnóstico interdisciplinario'), ('plan', 'Plan de restitución'), ('seguimiento', 'Seguimiento'), ('concluido', 'Proceso concluido')], default='ingreso', max_length=20),
        ),
        migrations.AddField(
            model_name='nna',
            name='nombre_preferido',
            field=models.CharField(blank=True, help_text='Nombre o apodo con el que prefiere que le llamen', max_length=80),
        ),
        migrations.AddField(
            model_name='padecimientonna',
            name='bajo_tratamiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='padecimientonna',
            name='diagnosticado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos_realizados', to='web.empleado'),
        ),
        migrations.AddField(
            model_name='padecimientonna',
            name='diagnostico_medico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='padecimientonna',
            name='estado_tratamiento',
            field=models.CharField(choices=[('sin_tratamiento', 'Sin tratamiento'), ('activo', 'En tratamiento'), ('controlado', 'Controlado'), ('suspendido', 'Tratamiento suspendido'), ('concluido', 'Tratamiento concluido')], default='sin_tratamiento', max_length=20),
        ),
        migrations.AddField(
            model_name='padecimientonna',
            name='requiere_medicamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nna',
            name='estatus',
            field=models.CharField(choices=[('activo', 'Activo — en atención'), ('inactivo', 'Inactivo'), ('egresado', 'Egresado'), ('suspendido', 'Suspendido temporalmente'), ('cerrado', 'Caso cerrado')], default='activo', max_length=20),
        ),
        migrations.CreateModel(
            name='IdiomaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('nativo', 'Nativo / Lengua materna')], default='nativo', max_length=20)),
                ('es_lengua_materna', models.BooleanField(default=False)),
                ('preferente', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='web.empleado')),
                ('lengua', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.lengua')),
                ('modo_adquisicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idiomas_empleado', to='web.modoadquisicionlengua')),
                ('nivel_competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idiomas_empleado', to='web.nivelcompetenciaoral')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.variantelinguistica')),
            ],
            options={
                'verbose_name': 'Idioma del Empleado',
                'verbose_name_plural': 'Idiomas de los Empleados',
                'unique_together': {('empleado', 'lengua', 'variante')},
            },
        ),
        migrations.CreateModel(
            name='IdiomaTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('nativo', 'Nativo / Lengua materna')], default='nativo', max_length=20)),
                ('es_lengua_materna', models.BooleanField(default=False)),
                ('preferente', models.BooleanField(default=False)),
                ('lengua', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.lengua')),
                ('modo_adquisicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idiomas_tutor', to='web.modoadquisicionlengua')),
                ('nivel_competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idiomas_tutor', to='web.nivelcompetenciaoral')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='web.tutor')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.variantelinguistica')),
            ],
            options={
                'verbose_name': 'Idioma del Tutor',
                'verbose_name_plural': 'Idiomas del Tutor',
                'unique_together': {('tutor', 'lengua', 'variante')},
            },
        ),
    ]
