# Generated by Django 5.2.11 on 2026-06-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_nna_estatus_proceso_nna_nombre_preferido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discapacidadnna',
            name='grado_dependencia',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='nna',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='nna',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='sexo',
        ),
    ]
