# Generated by Django 5.2.13 on 2026-06-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_redundant_5fn_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discapacidadnna',
            name='grado_dependencia_catalogo',
        ),
        migrations.AlterUniqueTogether(
            name='institucionejecutora',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='institucionejecutora',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='medidaproteccion',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='medidaproteccion',
            name='derecho_vulnerado',
        ),
        migrations.RemoveField(
            model_name='medidaproteccion',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='seguimientomedida',
            name='medida',
        ),
        migrations.RemoveField(
            model_name='seguimientomedida',
            name='registrado_por',
        ),
        migrations.RemoveField(
            model_name='solicitudarco',
            name='atendida_por',
        ),
        migrations.RemoveField(
            model_name='solicitudarco',
            name='nna',
        ),
        migrations.RemoveField(
            model_name='variantelinguistica',
            name='lengua',
        ),
        migrations.AlterUniqueTogether(
            name='idiomaempleado',
            unique_together={('empleado', 'lengua')},
        ),
        migrations.AlterUniqueTogether(
            name='idiomanna',
            unique_together={('nna', 'lengua')},
        ),
        migrations.AlterUniqueTogether(
            name='idiomatutor',
            unique_together={('tutor', 'lengua')},
        ),
        migrations.AddField(
            model_name='discapacidadnna',
            name='grado_dependencia',
            field=models.CharField(blank=True, choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('severa', 'Severa'), ('total', 'Total')], default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='ConsentimientoDatos',
        ),
        migrations.DeleteModel(
            name='GradoDependencia',
        ),
        migrations.DeleteModel(
            name='InstitucionEjecutora',
        ),
        migrations.DeleteModel(
            name='MedidaProteccion',
        ),
        migrations.DeleteModel(
            name='SeguimientoMedida',
        ),
        migrations.DeleteModel(
            name='SolicitudARCO',
        ),
        migrations.RemoveField(
            model_name='idiomaempleado',
            name='variante',
        ),
        migrations.RemoveField(
            model_name='idiomanna',
            name='variante',
        ),
        migrations.RemoveField(
            model_name='idiomatutor',
            name='variante',
        ),
        migrations.DeleteModel(
            name='VarianteLinguistica',
        ),
    ]
