# Generated by Django 5.2.13 on 2026-06-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_eliminar_tablas_redundantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiomanna',
            name='variante',
            field=models.CharField(blank=True, help_text="Variante específica (p. ej. 'Náhuatl de la Huasteca')", max_length=200),
        ),
    ]
