# Generated by Django 5.2.11 on 2026-06-23 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_idiomanna_add_variante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nna',
            name='estatus',
            field=models.CharField(choices=[('activo', 'Activo — en atención'), ('inactivo', 'Inactivo'), ('egresado', 'Egresado'), ('suspendido', 'Suspendido temporalmente')], default='activo', max_length=20),
        ),
        migrations.CreateModel(
            name='NNAEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('motivo_cambio', models.TextField(blank=True, help_text='Motivo del cambio de equipo (opcional)')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nna_historico', to='web.equipomultidisciplinario')),
                ('nna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_relacion', to='web.nna')),
            ],
            options={
                'verbose_name': 'Equipo del NNA',
                'verbose_name_plural': 'Equipos del NNA (historial)',
                'ordering': ['-activo', '-fecha_inicio'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('nna',), name='un_equipo_activo_por_nna')],
            },
        ),
    ]
